version: '3'
services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: naba
      MYSQL_USER: naba
      MYSQL_PASSWORD: naba
    volumes:
      - db_data:/var/lib/mysql
      - ./.files:/var/share/mysql-files
    ports:
      - 3306:3306
volumes:
  db_data:
