# fly.toml app configuration file generated for naba-data-dawn-cherry-7323 on 2024-07-01T21:21:58-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

primary_region = 'den'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = [ 'app' ]

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1

[mounts]
source = "data"
destination = "/usr/app/.data"
