import {
  index,
  integer,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

export const players = sqliteTable("players", {
  player_id: integer("player_id"),
  team_id: integer("team_id"),
  league_id: integer("league_id"),
  position: integer("position"),
  role: integer("role"),
  first_name: text("first_name"),
  last_name: text("last_name"),
  nick_name: text("nick_name"),
  age: integer("age"),
  date_of_birth: text("date_of_birth"),
  city_of_birth_id: integer("city_of_birth_id"),
  nation_id: integer("nation_id"),
  second_nation_id: integer("second_nation_id"),
  weight: integer("weight"),
  height: integer("height"),
  retired: integer("retired"),
  free_agent: integer("free_agent"),
  last_league_id: integer("last_league_id"),
  last_team_id: integer("last_team_id"),
  organization_id: integer("organization_id"),
  last_organization_id: integer("last_organization_id"),
  language_ids0: integer("language_ids0"),
  language_ids1: integer("language_ids1"),
  uniform_number: integer("uniform_number"),
  experience: integer("experience"),
  person_type: integer("person_type"),
  bats: integer("bats"),
  throws: integer("throws"),
  personality_greed: integer("personality_greed"),
  personality_loyalty: integer("personality_loyalty"),
  personality_play_for_winner: integer("personality_play_for_winner"),
  personality_work_ethic: integer("personality_work_ethic"),
  personality_intelligence: integer("personality_intelligence"),
  personality_leader: integer("personality_leader"),
  historical_id: integer("historical_id"),
  historical_team_id: integer("historical_team_id"),
  best_contract_offer_id: integer("best_contract_offer_id"),
  injury_is_injured: integer("injury_is_injured"),
  injury_dtd_injury: integer("injury_dtd_injury"),
  injury_career_ending: integer("injury_career_ending"),
  injury_dl_left: integer("injury_dl_left"),
  injury_dl_playoff_round: integer("injury_dl_playoff_round"),
  injury_left: integer("injury_left"),
  dtd_injury_effect: integer("dtd_injury_effect"),
  dtd_injury_effect_hit: integer("dtd_injury_effect_hit"),
  dtd_injury_effect_throw: integer("dtd_injury_effect_throw"),
  dtd_injury_effect_run: integer("dtd_injury_effect_run"),
  injury_id: integer("injury_id"),
  injury_id2: integer("injury_id2"),
  injury_dtd_injury2: integer("injury_dtd_injury2"),
  injury_left2: integer("injury_left2"),
  dtd_injury_effect2: integer("dtd_injury_effect2"),
  dtd_injury_effect_hit2: integer("dtd_injury_effect_hit2"),
  dtd_injury_effect_throw2: integer("dtd_injury_effect_throw2"),
  dtd_injury_effect_run2: integer("dtd_injury_effect_run2"),
  prone_overall: integer("prone_overall"),
  prone_leg: integer("prone_leg"),
  prone_back: integer("prone_back"),
  prone_arm: integer("prone_arm"),
  fatigue_pitches0: integer("fatigue_pitches0"),
  fatigue_pitches1: integer("fatigue_pitches1"),
  fatigue_pitches2: integer("fatigue_pitches2"),
  fatigue_pitches3: integer("fatigue_pitches3"),
  fatigue_pitches4: integer("fatigue_pitches4"),
  fatigue_pitches5: integer("fatigue_pitches5"),
  fatigue_points: integer("fatigue_points"),
  fatigue_played_today: integer("fatigue_played_today"),
  running_ratings_speed: integer("running_ratings_speed"),
  running_ratings_stealing: integer("running_ratings_stealing"),
  running_ratings_baserunning: integer("running_ratings_baserunning"),
  college: integer("college"),
  acquired: integer("acquired"),
  acquired_date: integer("acquired_date"),
  draft_year: integer("draft_year"),
  draft_round: integer("draft_round"),
  draft_supplemental: integer("draft_supplemental"),
  draft_pick: integer("draft_pick"),
  draft_overall_pick: integer("draft_overall_pick"),
  draft_eligible: integer("draft_eligible"),
  hsc_status: integer("hsc_status"),
  redshirt: integer("redshirt"),
  picked_in_draft: integer("picked_in_draft"),
  school: integer("school"),
  commit_school: integer("commit_school"),
  hidden: integer("hidden"),
  draft_league_id: integer("draft_league_id"),
  draft_team_id: integer("draft_team_id"),
  turned_coach: integer("turned_coach"),
  hall_of_fame: integer("hall_of_fame"),
  rust: integer("rust"),
  inducted: integer("inducted"),
  strategy_override_team: integer("strategy_override_team"),
  strategy_stealing: integer("strategy_stealing"),
  strategy_running: integer("strategy_running"),
  strategy_bunt_for_hit: integer("strategy_bunt_for_hit"),
  strategy_sac_bunt: integer("strategy_sac_bunt"),
  strategy_hit_run: integer("strategy_hit_run"),
  strategy_hook_start: integer("strategy_hook_start"),
  strategy_hook_relief: integer("strategy_hook_relief"),
  strategy_pitch_count: integer("strategy_pitch_count"),
  strategy_pitch_around: integer("strategy_pitch_around"),
  strategy_never_pinch_hit: integer("strategy_never_pinch_hit"),
  strategy_defensive_sub: integer("strategy_defensive_sub"),
  strategy_dtd_sit_min: integer("strategy_dtd_sit_min"),
  strategy_dtd_allow_ph: integer("strategy_dtd_allow_ph"),
  local_pop: integer("local_pop"),
  national_pop: integer("national_pop"),
  draft_protected: integer("draft_protected"),
  morale: integer("morale"),
  morale_player_performance: integer("morale_player_performance"),
  morale_team_performance: integer("morale_team_performance"),
  morale_team_transactions: integer("morale_team_transactions"),
  expectation: integer("expectation"),
  morale_player_role: integer("morale_player_role"),
  on_loan: integer("on_loan"),
  loan_league_id: integer("loan_league_id"),
  loan_team_id: integer("loan_team_id"),
}, (table) => {
  return {
    id_idx: uniqueIndex("id_idx").on(table.player_id),
    player_team_id_idx: index("player_team_id_idx").on(table.team_id),
  };
});
/*
export const cities = sqliteTable("cities", {
	cityId: text("city_id"),
	nationId: text("nation_id"),
	stateId: text("state_id"),
	name: text("name"),
	abbreviation: text("abbreviation"),
	latitude: text("latitude"),
	longitude: text("longitude"),
	population: text("population"),
	mainLanguageId: text("main_language_id"),
});

export const coaches = sqliteTable("coaches", {
	coachId: text("coach_id"),
	firstName: text("first_name"),
	lastName: text("last_name"),
	nickName: text("nick_name"),
	age: text("age"),
	dateOfBirth: text("date_of_birth"),
	cityOfBirthId: text("city_of_birth_id"),
	nationId: text("nation_id"),
	weight: text("weight"),
	height: text("height"),
	position: text("position"),
	experience: text("experience"),
	occupation: text("occupation"),
	teamId: text("team_id"),
	formerPlayerId: text("former_player_id"),
	quickLeft: text("quick_left"),
	contractSalary: text("contract_salary"),
	contractYears: text("contract_years"),
	contractExtensionSalary: text("contract_extension_salary"),
	contractExtensionYears: text("contract_extension_years"),
	scoutMajor: text("scout_major"),
	scoutMinor: text("scout_minor"),
	scoutInternational: text("scout_international"),
	scoutAmateur: text("scout_amateur"),
	scoutAmateurPreference: text("scout_amateur_preference"),
	teachHitting: text("teach_hitting"),
	teachPitching: text("teach_pitching"),
	teachC: text("teach_c"),
	teachIf: text("teach_if"),
	teachOf: text("teach_of"),
	handleVeterans: text("handle_veterans"),
	handleRookies: text("handle_rookies"),
	handlePlayers: text("handle_players"),
	healLegs: text("heal_legs"),
	healArms: text("heal_arms"),
	healBack: text("heal_back"),
	healOther: text("heal_other"),
	healRest: text("heal_rest"),
	managementStyle: text("management_style"),
	personality: text("personality"),
	hittingFocus: text("hitting_focus"),
	pitchingFocus: text("pitching_focus"),
	trainingFocus: text("training_focus"),
	teachRunning: text("teach_running"),
	preventLegs: text("prevent_legs"),
	preventArms: text("prevent_arms"),
	preventBack: text("prevent_back"),
	preventOther: text("prevent_other"),
	stealing: text("stealing"),
	running: text("running"),
	pinchrun: text("pinchrun"),
	pinchhitPos: text("pinchhit_pos"),
	pinchhitPitch: text("pinchhit_pitch"),
	hookStart: text("hook_start"),
	hookRelief: text("hook_relief"),
	closer: text("closer"),
	lrMatchup: text("lr_matchup"),
	buntHit: text("bunt_hit"),
	bunt: text("bunt"),
	hitRun: text("hit_run"),
	runHit: text("run_hit"),
	squeeze: text("squeeze"),
	pitchAround: text("pitch_around"),
	intentionalWalk: text("intentional_walk"),
	holdRunner: text("hold_runner"),
	guardLines: text("guard_lines"),
	infieldIn: text("infield_in"),
	outfieldIn: text("outfield_in"),
	cornersIn: text("corners_in"),
	shiftIf: text("shift_if"),
	shiftOf: text("shift_of"),
	opener: text("opener"),
	numPitchers: text("num_pitchers"),
	numHitters: text("num_hitters"),
	favorSpeedToPower: text("favor_speed_to_power"),
	favorAvgToObp: text("favor_avg_to_obp"),
	favorDefenseToOffense: text("favor_defense_to_offense"),
	favorPitchingToHitting: text("favor_pitching_to_hitting"),
	favorVeteransToProspects: text("favor_veterans_to_prospects"),
	tradeAggressiveness: text("trade_aggressiveness"),
	playerLoyalty: text("player_loyalty"),
	tradeFrequency: text("trade_frequency"),
	tradePreference: text("trade_preference"),
	valueStats: text("value_stats"),
	valueThisYear: text("value_this_year"),
	valueLastYear: text("value_last_year"),
	valueTwoYears: text("value_two_years"),
	draftValue: text("draft_value"),
	intlFaValue: text("intl_fa_value"),
	developValue: text("develop_value"),
	ratingsValue: text("ratings_value"),
	managerValue: text("manager_value"),
	pitchingCoachValue: text("pitching_coach_value"),
	hittingCoachValue: text("hitting_coach_value"),
	scoutValue: text("scout_value"),
	doctorValue: text("doctor_value"),
	basecoachValue: text("basecoach_value"),
	positiveRelation: text("positive_relation"),
	negativeRelation: text("negative_relation"),
});

export const continents = sqliteTable("continents", {
	continentId: text("continent_id"),
	name: text("name"),
	abbreviation: text("abbreviation"),
	demonym: text("demonym"),
	population: text("population"),
	mainLanguageId: text("main_language_id"),
});

export const divisions = sqliteTable("divisions", {
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	divisionId: text("division_id"),
	name: text("name"),
	gender: text("gender"),
});

export const games = sqliteTable("games", {
	gameId: text("game_id"),
	leagueId: text("league_id"),
	homeTeam: text("home_team"),
	awayTeam: text("away_team"),
	attendance: text("attendance"),
	date: text("date"),
	time: text("time"),
	gameType: text("game_type"),
	played: text("played"),
	innings: text("innings"),
	runs0: text("runs0"),
	runs1: text("runs1"),
	hits0: text("hits0"),
	hits1: text("hits1"),
	errors0: text("errors0"),
	errors1: text("errors1"),
	winningPitcher: text("winning_pitcher"),
	losingPitcher: text("losing_pitcher"),
	savePitcher: text("save_pitcher"),
	starter0: text("starter0"),
	starter1: text("starter1"),
});

export const gamesScore = sqliteTable("games_score", {
	gameId: text("game_id"),
	team: text("team"),
	inning: text("inning"),
	score: text("score"),
});

export const humanManagerHistory = sqliteTable("human_manager_history", {
	humanManagerId: text("human_manager_id"),
	teamId: text("team_id"),
	year: text("year"),
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	divisionId: text("division_id"),
	bestHitterId: text("best_hitter_id"),
	bestPitcherId: text("best_pitcher_id"),
	bestRookieId: text("best_rookie_id"),
	managerId: text("manager_id"),
	madePlayoffs: text("made_playoffs"),
	wonPlayoffs: text("won_playoffs"),
	fired: text("fired"),
	positionInDivision: text("position_in_division"),
});

export const humanManagerHistoryBattingStats = sqliteTable("human_manager_history_batting_stats", {
	humanManagerId: text("human_manager_id"),
	teamId: text("team_id"),
	year: text("year"),
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	divisionId: text("division_id"),
	levelId: text("level_id"),
	splitId: text("split_id"),
	pa: text("pa"),
	ab: text("ab"),
	h: text("h"),
	k: text("k"),
	tb: text("tb"),
	s: text("s"),
	d: text("d"),
	t: text("t"),
	hr: text("hr"),
	sb: text("sb"),
	cs: text("cs"),
	rbi: text("rbi"),
	r: text("r"),
	bb: text("bb"),
	ibb: text("ibb"),
	hp: text("hp"),
	sh: text("sh"),
	sf: text("sf"),
	ci: text("ci"),
	gdp: text("gdp"),
	g: text("g"),
	gs: text("gs"),
	ebh: text("ebh"),
	pitchesSeen: text("pitches_seen"),
	avg: text("avg"),
	obp: text("obp"),
	slg: text("slg"),
	rc: text("rc"),
	rc27: text("rc27"),
	iso: text("iso"),
	tavg: text("tavg"),
	woba: text("woba"),
	ops: text("ops"),
	sbp: text("sbp"),
});

export const humanManagerHistoryFieldingStatsStats = sqliteTable("human_manager_history_fielding_stats_stats", {
	humanManagerId: text("human_manager_id"),
	teamId: text("team_id"),
	year: text("year"),
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	divisionId: text("division_id"),
	levelId: text("level_id"),
	splitId: text("split_id"),
	position: text("position"),
	g: text("g"),
	gs: text("gs"),
	tc: text("tc"),
	a: text("a"),
	po: text("po"),
	e: text("e"),
	dp: text("dp"),
	tp: text("tp"),
	pb: text("pb"),
	sba: text("sba"),
	rto: text("rto"),
	er: text("er"),
	ip: text("ip"),
	ipf: text("ipf"),
	pct: text("pct"),
	range: text("range"),
	rtop: text("rtop"),
	cera: text("cera"),
});

export const humanManagerHistoryFinancials = sqliteTable("human_manager_history_financials", {
	humanManagerId: text("human_manager_id"),
	teamId: text("team_id"),
	year: text("year"),
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	divisionId: text("division_id"),
	gateRevenue: text("gate_revenue"),
	mediaRevenue: text("media_revenue"),
	merchandisingRevenue: text("merchandising_revenue"),
	otherRevenue: text("other_revenue"),
	revenueSharing: text("revenue_sharing"),
	luxurySharing: text("luxury_sharing"),
	playoffRevenue: text("playoff_revenue"),
	cash: text("cash"),
	playerExpenses: text("player_expenses"),
	staffExpenses: text("staff_expenses"),
	stadiumExpenses: text("stadium_expenses"),
	attendance: text("attendance"),
	fanInterest: text("fan_interest"),
	fanLoyalty: text("fan_loyalty"),
	fanModifier: text("fan_modifier"),
	ticketPrice: text("ticket_price"),
	budget: text("budget"),
	market: text("market"),
	ownerExpectation: text("owner_expectation"),
});

export const humanManagerHistoryPitchingStats = sqliteTable("human_manager_history_pitching_stats", {
	humanManagerId: text("human_manager_id"),
	teamId: text("team_id"),
	year: text("year"),
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	divisionId: text("division_id"),
	levelId: text("level_id"),
	splitId: text("split_id"),
	ab: text("ab"),
	ip: text("ip"),
	bf: text("bf"),
	tb: text("tb"),
	ha: text("ha"),
	k: text("k"),
	rs: text("rs"),
	bb: text("bb"),
	r: text("r"),
	er: text("er"),
	gb: text("gb"),
	fb: text("fb"),
	pi: text("pi"),
	ipf: text("ipf"),
	g: text("g"),
	gs: text("gs"),
	w: text("w"),
	l: text("l"),
	s: text("s"),
	sa: text("sa"),
	da: text("da"),
	sh: text("sh"),
	sf: text("sf"),
	ta: text("ta"),
	hra: text("hra"),
	bk: text("bk"),
	ci: text("ci"),
	iw: text("iw"),
	wp: text("wp"),
	hp: text("hp"),
	gf: text("gf"),
	dp: text("dp"),
	qs: text("qs"),
	svo: text("svo"),
	bs: text("bs"),
	ra: text("ra"),
	cg: text("cg"),
	sho: text("sho"),
	sb: text("sb"),
	cs: text("cs"),
	hld: text("hld"),
	r9: text("r9"),
	avg: text("avg"),
	obp: text("obp"),
	slg: text("slg"),
	ops: text("ops"),
	h9: text("h9"),
	k9: text("k9"),
	hr9: text("hr9"),
	bb9: text("bb9"),
	cgp: text("cgp"),
	cera: text("cera"),
	fip: text("fip"),
	qsp: text("qsp"),
	winp: text("winp"),
	rsg: text("rsg"),
	svp: text("svp"),
	bsvp: text("bsvp"),
	gfp: text("gfp"),
	era: text("era"),
	pig: text("pig"),
	ws: text("ws"),
	whip: text("whip"),
	gbfbp: text("gbfbp"),
	kbb: text("kbb"),
	babip: text("babip"),
});

export const humanManagerHistoryRecord = sqliteTable("human_manager_history_record", {
	humanManagerId: text("human_manager_id"),
	teamId: text("team_id"),
	year: text("year"),
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	divisionId: text("division_id"),
	g: text("g"),
	w: text("w"),
	l: text("l"),
	pos: text("pos"),
	pct: text("pct"),
	gb: text("gb"),
	streak: text("streak"),
	magicNumber: text("magic_number"),
});

export const humanManagers = sqliteTable("human_managers", {
	humanManagerId: text("human_manager_id"),
	isCommish: text("is_commish"),
	firstName: text("first_name"),
	lastName: text("last_name"),
	nickName: text("nick_name"),
	age: text("age"),
	dateOfBirth: text("date_of_birth"),
	cityOfBirthId: text("city_of_birth_id"),
	nationId: text("nation_id"),
	secondNationId: text("second_nation_id"),
	weight: text("weight"),
	height: text("height"),
	retired: text("retired"),
	freeAgent: text("free_agent"),
	leagueId: text("league_id"),
	lastLeagueId: text("last_league_id"),
	teamId: text("team_id"),
	lastTeamId: text("last_team_id"),
	organizationId: text("organization_id"),
	lastOrganizationId: text("last_organization_id"),
	languageIds0: text("language_ids0"),
	languageIds1: text("language_ids1"),
	uniformNumber: text("uniform_number"),
	experience: text("experience"),
	personType: text("person_type"),
	bats: text("bats"),
	throws: text("throws"),
	personalityGreed: text("personality_greed"),
	personalityLoyalty: text("personality_loyalty"),
	personalityPlayForWinner: text("personality_play_for_winner"),
	personalityWorkEthic: text("personality_work_ethic"),
	personalityIntelligence: text("personality_intelligence"),
	personalityLeader: text("personality_leader"),
});

export const languageData = sqliteTable("language_data", {
	parentTable: text("parent_table"),
	parentId: text("parent_id"),
	languageId: text("language_id"),
	percentage: text("percentage"),
});

export const languages = sqliteTable("languages", {
	languageId: text("language_id"),
	name: text("name"),
});

export const leagueEvents = sqliteTable("league_events", {
	leagueId: text("league_id"),
	startDate: text("start_date"),
	type: text("type"),
	eventOver: text("event_over"),
	deleted: text("deleted"),
	name: text("name"),
	needsHumanAction: text("needs_human_action"),
	realSimDate: text("real_sim_date"),
});

export const leagueHistory = sqliteTable("league_history", {
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	year: text("year"),
	bestHitterId: text("best_hitter_id"),
	bestPitcherId: text("best_pitcher_id"),
	bestRookieId: text("best_rookie_id"),
	bestManagerId: text("best_manager_id"),
	bestFielderId0: text("best_fielder_id0"),
	bestFielderId1: text("best_fielder_id1"),
	bestFielderId2: text("best_fielder_id2"),
	bestFielderId3: text("best_fielder_id3"),
	bestFielderId4: text("best_fielder_id4"),
	bestFielderId5: text("best_fielder_id5"),
	bestFielderId6: text("best_fielder_id6"),
	bestFielderId7: text("best_fielder_id7"),
	bestFielderId8: text("best_fielder_id8"),
	bestFielderId9: text("best_fielder_id9"),
});

export const leagueHistoryAllStar = sqliteTable("league_history_all_star", {
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	year: text("year"),
	allStarPos: text("all_star_pos"),
	allStar: text("all_star"),
});

export const leagueHistoryBattingStats = sqliteTable("league_history_batting_stats", {
	year: text("year"),
	teamId: text("team_id"),
	gameId: text("game_id"),
	leagueId: text("league_id"),
	levelId: text("level_id"),
	splitId: text("split_id"),
	pa: text("pa"),
	ab: text("ab"),
	h: text("h"),
	k: text("k"),
	tb: text("tb"),
	s: text("s"),
	d: text("d"),
	t: text("t"),
	hr: text("hr"),
	sb: text("sb"),
	cs: text("cs"),
	rbi: text("rbi"),
	r: text("r"),
	bb: text("bb"),
	ibb: text("ibb"),
	hp: text("hp"),
	sh: text("sh"),
	sf: text("sf"),
	ci: text("ci"),
	gdp: text("gdp"),
	g: text("g"),
	gs: text("gs"),
	ebh: text("ebh"),
	pitchesSeen: text("pitches_seen"),
	avg: text("avg"),
	obp: text("obp"),
	slg: text("slg"),
	rc: text("rc"),
	rc27: text("rc27"),
	iso: text("iso"),
	woba: text("woba"),
	ops: text("ops"),
	sbp: text("sbp"),
	kp: text("kp"),
	bbp: text("bbp"),
	wpa: text("wpa"),
	babip: text("babip"),
});

export const leagueHistoryFieldingStats = sqliteTable("league_history_fielding_stats", {
	year: text("year"),
	teamId: text("team_id"),
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	levelId: text("level_id"),
	splitId: text("split_id"),
	position: text("position"),
	g: text("g"),
	gs: text("gs"),
	tc: text("tc"),
	a: text("a"),
	po: text("po"),
	e: text("e"),
	dp: text("dp"),
	tp: text("tp"),
	pb: text("pb"),
	sba: text("sba"),
	rto: text("rto"),
	er: text("er"),
	ip: text("ip"),
	ipf: text("ipf"),
	pct: text("pct"),
	range: text("range"),
	rtop: text("rtop"),
	cera: text("cera"),
	zr: text("zr"),
	plays: text("plays"),
	playsBase: text("plays_base"),
	roe: text("roe"),
	eff: text("eff"),
	opps0: text("opps_0"),
	oppsMade0: text("opps_made_0"),
	opps1: text("opps_1"),
	oppsMade1: text("opps_made_1"),
	opps2: text("opps_2"),
	oppsMade2: text("opps_made_2"),
	opps3: text("opps_3"),
	oppsMade3: text("opps_made_3"),
	opps4: text("opps_4"),
	oppsMade4: text("opps_made_4"),
	opps5: text("opps_5"),
	oppsMade5: text("opps_made_5"),
	framing: text("framing"),
	arm: text("arm"),
});

export const leagueHistoryPitchingStats = sqliteTable("league_history_pitching_stats", {
	year: text("year"),
	teamId: text("team_id"),
	gameId: text("game_id"),
	leagueId: text("league_id"),
	levelId: text("level_id"),
	splitId: text("split_id"),
	ab: text("ab"),
	ip: text("ip"),
	bf: text("bf"),
	tb: text("tb"),
	ha: text("ha"),
	k: text("k"),
	rs: text("rs"),
	bb: text("bb"),
	r: text("r"),
	er: text("er"),
	gb: text("gb"),
	fb: text("fb"),
	pi: text("pi"),
	ipf: text("ipf"),
	g: text("g"),
	gs: text("gs"),
	w: text("w"),
	l: text("l"),
	s: text("s"),
	sa: text("sa"),
	da: text("da"),
	sh: text("sh"),
	sf: text("sf"),
	ta: text("ta"),
	hra: text("hra"),
	bk: text("bk"),
	ci: text("ci"),
	iw: text("iw"),
	wp: text("wp"),
	hp: text("hp"),
	gf: text("gf"),
	dp: text("dp"),
	qs: text("qs"),
	svo: text("svo"),
	bs: text("bs"),
	ra: text("ra"),
	ir: text("ir"),
	irs: text("irs"),
	cg: text("cg"),
	sho: text("sho"),
	sb: text("sb"),
	cs: text("cs"),
	hld: text("hld"),
	r9: text("r9"),
	avg: text("avg"),
	obp: text("obp"),
	slg: text("slg"),
	ops: text("ops"),
	h9: text("h9"),
	k9: text("k9"),
	kp: text("kp"),
	bbp: text("bbp"),
	kbbp: text("kbbp"),
	hr9: text("hr9"),
	bb9: text("bb9"),
	cgp: text("cgp"),
	fip: text("fip"),
	qsp: text("qsp"),
	winp: text("winp"),
	rsg: text("rsg"),
	svp: text("svp"),
	bsvp: text("bsvp"),
	irsp: text("irsp"),
	gfp: text("gfp"),
	era: text("era"),
	pig: text("pig"),
	ws: text("ws"),
	whip: text("whip"),
	gbfbp: text("gbfbp"),
	kbb: text("kbb"),
	babip: text("babip"),
	wpa: text("wpa"),
	war: text("war"),
	ra9War: text("ra9war"),
	sd: text("sd"),
	md: text("md"),
});

export const leaguePlayoffFixtures = sqliteTable("league_playoff_fixtures", {
	leagueId: text("league_id"),
	teamId0: text("team_id0"),
	teamId1: text("team_id1"),
	winner: text("winner"),
	finished: text("finished"),
	bestOf: text("best_of"),
	played: text("played"),
	round: text("round"),
	result0: text("result0"),
	result1: text("result1"),
});

export const leaguePlayoffs = sqliteTable("league_playoffs", {
	leagueId: text("league_id"),
	playOffMode: text("play_off_mode"),
	round: text("round"),
	maxRound: text("max_round"),
	numWildCards: text("num_wild_cards"),
	bestOf0: text("best_of0"),
	bestOf1: text("best_of1"),
	bestOf2: text("best_of2"),
	bestOf3: text("best_of3"),
	bestOf4: text("best_of4"),
	bestOf5: text("best_of5"),
	bestOf6: text("best_of6"),
	bestOf7: text("best_of7"),
	bestOf8: text("best_of8"),
	bestOf9: text("best_of9"),
	bestOf10: text("best_of10"),
	bestOf11: text("best_of11"),
	bestOf12: text("best_of12"),
	bestOf13: text("best_of13"),
	bestOf14: text("best_of14"),
	bestOf15: text("best_of15"),
	bestOf16: text("best_of16"),
	bestOf17: text("best_of17"),
	bestOf18: text("best_of18"),
	bestOf19: text("best_of19"),
	bestOf20: text("best_of20"),
	bestOf21: text("best_of21"),
	bestOf22: text("best_of22"),
	bestOf23: text("best_of23"),
	bestOf24: text("best_of24"),
	bestOf25: text("best_of25"),
	bestOf26: text("best_of26"),
	bestOf27: text("best_of27"),
	bestOf28: text("best_of28"),
	bestOf29: text("best_of29"),
	bestOf30: text("best_of30"),
	bestOf31: text("best_of31"),
	bestOf32: text("best_of32"),
	bestOf33: text("best_of33"),
	bestOf34: text("best_of34"),
	bestOf35: text("best_of35"),
	bestOf36: text("best_of36"),
	bestOf37: text("best_of37"),
	bestOf38: text("best_of38"),
	bestOf39: text("best_of39"),
	bestOf40: text("best_of40"),
	bestOf41: text("best_of41"),
	bestOf42: text("best_of42"),
	bestOf43: text("best_of43"),
	bestOf44: text("best_of44"),
	bestOf45: text("best_of45"),
	bestOf46: text("best_of46"),
	bestOf47: text("best_of47"),
	bestOf48: text("best_of48"),
	bestOf49: text("best_of49"),
	roundNames0: text("round_names0"),
	roundNames1: text("round_names1"),
	roundNames2: text("round_names2"),
	roundNames3: text("round_names3"),
	roundNames4: text("round_names4"),
	roundNames5: text("round_names5"),
	roundNames6: text("round_names6"),
	roundNames7: text("round_names7"),
	roundNames8: text("round_names8"),
	roundNames9: text("round_names9"),
	roundNames10: text("round_names10"),
	roundNames11: text("round_names11"),
	roundNames12: text("round_names12"),
	roundNames13: text("round_names13"),
	roundNames14: text("round_names14"),
	roundNames15: text("round_names15"),
	roundNames16: text("round_names16"),
	roundNames17: text("round_names17"),
	roundNames18: text("round_names18"),
	roundNames19: text("round_names19"),
	roundNames20: text("round_names20"),
	roundNames21: text("round_names21"),
	roundNames22: text("round_names22"),
	roundNames23: text("round_names23"),
	roundNames24: text("round_names24"),
	roundNames25: text("round_names25"),
	roundNames26: text("round_names26"),
	roundNames27: text("round_names27"),
	roundNames28: text("round_names28"),
	roundNames29: text("round_names29"),
	roundNames30: text("round_names30"),
	roundNames31: text("round_names31"),
	roundNames32: text("round_names32"),
	roundNames33: text("round_names33"),
	roundNames34: text("round_names34"),
	roundNames35: text("round_names35"),
	roundNames36: text("round_names36"),
	roundNames37: text("round_names37"),
	roundNames38: text("round_names38"),
	roundNames39: text("round_names39"),
	roundNames40: text("round_names40"),
	roundNames41: text("round_names41"),
	roundNames42: text("round_names42"),
	roundNames43: text("round_names43"),
	roundNames44: text("round_names44"),
	roundNames45: text("round_names45"),
	roundNames46: text("round_names46"),
	roundNames47: text("round_names47"),
	roundNames48: text("round_names48"),
	roundNames49: text("round_names49"),
	splitSeason: text("split_season"),
	allstarWinnerHomefield: text("allstar_winner_homefield"),
	allstarWinner: text("allstar_winner"),
	winner: text("winner"),
});

export const leagues = sqliteTable("leagues", {
	leagueId: text("league_id"),
	name: text("name"),
	abbr: text("abbr"),
	nationId: text("nation_id"),
	languageId: text("language_id"),
	gender: text("gender"),
	historicalLeague: text("historical_league"),
	logoFileName: text("logo_file_name"),
	playersPath: text("players_path"),
	startDate: text("start_date"),
	preferredStartDate: text("preferred_start_date"),
	pitcherAwardName: text("pitcher_award_name"),
	mvpAwardName: text("mvp_award_name"),
	rookieAwardName: text("rookie_award_name"),
	defenseAwardName: text("defense_award_name"),
	fictionalPlayers: text("fictional_players"),
	startFantasyDraft: text("start_fantasy_draft"),
	tradingDeadline: text("trading_deadline"),
	winterMeetings: text("winter_meetings"),
	arbitrationOffering: text("arbitration_offering"),
	showDraftPool: text("show_draft_pool"),
	rostersExpanded: text("rosters_expanded"),
	draftDate: text("draft_date"),
	rule5DraftDate: text("rule_5_draft_date"),
	internationalFaDate: text("international_fa_date"),
	rosterExpandDate: text("roster_expand_date"),
	tradeDeadlineDate: text("trade_deadline_date"),
	allstarDate: text("allstar_date"),
	daysUntilDeadline: text("days_until_deadline"),
	nextDraftType: text("next_draft_type"),
	parentLeagueId: text("parent_league_id"),
	leagueState: text("league_state"),
	seasonYear: text("season_year"),
	historicalYear: text("historical_year"),
	leagueLevel: text("league_level"),
	statsDetail: text("stats_detail"),
	historicalImportPath: text("historical_import_path"),
	foreignerPercentage: text("foreigner_percentage"),
	wasOotp6: text("was_ootp6"),
	was65: text("was_65"),
	allstarGame: text("allstar_game"),
	autoScheduleAllstar: text("auto_schedule_allstar"),
	allstarTeamId0: text("allstar_team_id0"),
	allstarTeamId1: text("allstar_team_id1"),
	scheduleFile1: text("schedule_file_1"),
	scheduleFile2: text("schedule_file_2"),
	rulesRule5: text("rules_rule_5"),
	rulesMinorLeagueOptions: text("rules_minor_league_options"),
	rulesTrading: text("rules_trading"),
	rulesTradingDeadlineEvents: text("rules_trading_deadline_events"),
	rulesDraftPickTrading: text("rules_draft_pick_trading"),
	rulesFinancials: text("rules_financials"),
	rulesAmateurDraft: text("rules_amateur_draft"),
	rulesFaCompensation: text("rules_fa_compensation"),
	rulesScheduleBalanced: text("rules_schedule_balanced"),
	rulesScheduleInterLeague: text("rules_schedule_inter_league"),
	rulesScheduleForceStartDay: text("rules_schedule_force_start_day"),
	rulesTradesOtherLeagues: text("rules_trades_other_leagues"),
	rulesFreeAgentsFromOtherLeagues: text("rules_free_agents_from_other_leagues"),
	rulesFreeAgentsLeaveOtherLeagues: text("rules_free_agents_leave_other_leagues"),
	rulesAllstarGame: text("rules_allstar_game"),
	rulesSpringTraining: text("rules_spring_training"),
	rulesActiveRosterLimit: text("rules_active_roster_limit"),
	rulesSecondaryRosterLimit: text("rules_secondary_roster_limit"),
	rulesExpandedRosterLimit: text("rules_expanded_roster_limit"),
	rulesMinServiceDays: text("rules_min_service_days"),
	rulesWaiverPeriodLength: text("rules_waiver_period_length"),
	rulesDfaPeriodLength: text("rules_dfa_period_length"),
	rulesFaMinimumYears: text("rules_fa_minimum_years"),
	rulesSalaryArbitrationMinimumYears: text("rules_salary_arbitration_minimum_years"),
	rulesMinorLeagueFaMinimumYears: text("rules_minor_league_fa_minimum_years"),
	rulesForeignerLimit: text("rules_foreigner_limit"),
	rulesForeignerPitcherLimit: text("rules_foreigner_pitcher_limit"),
	rulesForeignerHitterLimit: text("rules_foreigner_hitter_limit"),
	rulesScheduleGamesPerTeam: text("rules_schedule_games_per_team"),
	rulesScheduleTypicalSeries: text("rules_schedule_typical_series"),
	rulesScheduleGameTimes: text("rules_schedule_game_times"),
	rulesSchedulePreferredStartDay: text("rules_schedule_preferred_start_day"),
	rulesAmateurDraftRounds: text("rules_amateur_draft_rounds"),
	rulesMinimumSalary: text("rules_minimum_salary"),
	rulesSalaryCap: text("rules_salary_cap"),
	rulesPlayerSalary0: text("rules_player_salary0"),
	rulesPlayerSalary1: text("rules_player_salary1"),
	rulesPlayerSalary2: text("rules_player_salary2"),
	rulesPlayerSalary3: text("rules_player_salary3"),
	rulesPlayerSalary4: text("rules_player_salary4"),
	rulesPlayerSalary5: text("rules_player_salary5"),
	rulesPlayerSalary6: text("rules_player_salary6"),
	rulesPlayerSalary7: text("rules_player_salary7"),
	rulesAverageCoachSalary: text("rules_average_coach_salary"),
	rulesAverageAttendance: text("rules_average_attendance"),
	rulesAverageNationalMediaContract: text("rules_average_national_media_contract"),
	rulesCashMaximum: text("rules_cash_maximum"),
	rulesAverageTicketPrice: text("rules_average_ticket_price"),
	rulesLuxurySharing: text("rules_luxury_sharing"),
	rulesRevenueSharing: text("rules_revenue_sharing"),
	rulesRevenueSharingTax: text("rules_revenue_sharing_tax"),
	rulesLuxurySharingCap: text("rules_luxury_sharing_cap"),
	rulesLuxuryTax: text("rules_luxury_tax"),
	rulesNationalMediaContractFixed: text("rules_national_media_contract_fixed"),
	rulesOwnerDecidesBudget: text("rules_owner_decides_budget"),
	rulesScheduleAutoAdjustDates: text("rules_schedule_auto_adjust_dates"),
	rulesHistoricalImportRookies: text("rules_historical_import_rookies"),
	avgRatingContact: text("avg_rating_contact"),
	avgRatingGap: text("avg_rating_gap"),
	avgRatingPower: text("avg_rating_power"),
	avgRatingEye: text("avg_rating_eye"),
	avgRatingStrikeouts: text("avg_rating_strikeouts"),
	avgRatingStuff: text("avg_rating_stuff"),
	avgRatingMovement: text("avg_rating_movement"),
	avgRatingControl: text("avg_rating_control"),
	avgRatingFielding0: text("avg_rating_fielding0"),
	avgRatingFielding1: text("avg_rating_fielding1"),
	avgRatingFielding2: text("avg_rating_fielding2"),
	avgRatingFielding3: text("avg_rating_fielding3"),
	avgRatingFielding4: text("avg_rating_fielding4"),
	avgRatingFielding5: text("avg_rating_fielding5"),
	avgRatingFielding6: text("avg_rating_fielding6"),
	avgRatingFielding7: text("avg_rating_fielding7"),
	avgRatingFielding8: text("avg_rating_fielding8"),
	avgRatingFielding9: text("avg_rating_fielding9"),
	avgRatingOverall: text("avg_rating_overall"),
	avgRatingAge: text("avg_rating_age"),
	leagueTotalsAb: text("league_totals_ab"),
	leagueTotalsH: text("league_totals_h"),
	leagueTotalsD: text("league_totals_d"),
	leagueTotalsT: text("league_totals_t"),
	leagueTotalsHr: text("league_totals_hr"),
	leagueTotalsBb: text("league_totals_bb"),
	leagueTotalsHp: text("league_totals_hp"),
	leagueTotalsK: text("league_totals_k"),
	leagueTotalsPa: text("league_totals_pa"),
	leagueTotalsBabip: text("league_totals_babip"),
	leagueTotalsModH: text("league_totals_mod_h"),
	leagueTotalsModD: text("league_totals_mod_d"),
	leagueTotalsModT: text("league_totals_mod_t"),
	leagueTotalsModHr: text("league_totals_mod_hr"),
	leagueTotalsModBb: text("league_totals_mod_bb"),
	leagueTotalsModHp: text("league_totals_mod_hp"),
	leagueTotalsModK: text("league_totals_mod_k"),
	leagueTotalsModBabip: text("league_totals_mod_babip"),
	mlEquivalenciesAvg: text("ml_equivalencies_avg"),
	mlEquivalenciesHr: text("ml_equivalencies_hr"),
	mlEquivalenciesEb: text("ml_equivalencies_eb"),
	mlEquivalenciesBb: text("ml_equivalencies_bb"),
	mlEquivalenciesK: text("ml_equivalencies_k"),
	mlEquivalenciesHp: text("ml_equivalencies_hp"),
	playerCreationModifierContact: text("player_creation_modifier_contact"),
	playerCreationModifierGap: text("player_creation_modifier_gap"),
	playerCreationModifierPower: text("player_creation_modifier_power"),
	playerCreationModifierEye: text("player_creation_modifier_eye"),
	playerCreationModifierStrikeouts: text("player_creation_modifier_strikeouts"),
	playerCreationModifierStuff: text("player_creation_modifier_stuff"),
	playerCreationModifierMovement: text("player_creation_modifier_movement"),
	playerCreationModifierControl: text("player_creation_modifier_control"),
	playerCreationModifierSpeed: text("player_creation_modifier_speed"),
	playerCreationModifierFielding: text("player_creation_modifier_fielding"),
	financialCoefficient: text("financial_coefficient"),
	worldStartYear: text("world_start_year"),
	currentDate: text("current_date"),
	backgroundColorId: text("background_color_id"),
	textColorId: text("text_color_id"),
	scoutingCoachId: text("scouting_coach_id"),
});

export const messages = sqliteTable("messages", {
	messageId: text("message_id"),
	subject: text("subject"),
	playerId0: text("player_id_0"),
	playerId1: text("player_id_1"),
	playerId2: text("player_id_2"),
	playerId3: text("player_id_3"),
	playerId4: text("player_id_4"),
	playerId5: text("player_id_5"),
	playerId6: text("player_id_6"),
	playerId7: text("player_id_7"),
	playerId8: text("player_id_8"),
	playerId9: text("player_id_9"),
	teamId0: text("team_id_0"),
	teamId1: text("team_id_1"),
	teamId2: text("team_id_2"),
	teamId3: text("team_id_3"),
	teamId4: text("team_id_4"),
	leagueId0: text("league_id_0"),
	leagueId1: text("league_id_1"),
	importance: text("importance"),
	messageType: text("message_type"),
	hype: text("hype"),
	senderType: text("sender_type"),
	senderId: text("sender_id"),
	recipientId: text("recipient_id"),
	tradeId: text("trade_id"),
	date: text("date"),
	deleted: text("deleted"),
	notify: text("notify"),
	ongoingStoryId: text("ongoing_story_id"),
	textIsModified: text("text_is_modified"),
	body: text("body"),
});

export const nations = sqliteTable("nations", {
	nationId: text("nation_id"),
	name: text("name"),
	shortName: text("short_name"),
	abbreviation: text("abbreviation"),
	demonym: text("demonym"),
	population: text("population"),
	gender: text("gender"),
	baseballQuality: text("baseball_quality"),
	continentId: text("continent_id"),
	mainLanguageId: text("main_language_id"),
	qualityTotal: text("quality_total"),
	capitalId: text("capital_id"),
	useHardcodedMlPlayerOrigins: text("use_hardcoded_ml_player_origins"),
	thisIsTheUsa: text("this_is_the_usa"),
});

export const parks = sqliteTable("parks", {
	parkId: text("park_id"),
	dimensionsX: text("dimensions_x"),
	dimensionsY: text("dimensions_y"),
	batterLeftX: text("batter_left_x"),
	batterLeftY: text("batter_left_y"),
	batterRightX: text("batter_right_x"),
	batterRightY: text("batter_right_y"),
	basesX0: text("bases_x0"),
	basesX1: text("bases_x1"),
	basesX2: text("bases_x2"),
	basesY0: text("bases_y0"),
	basesY1: text("bases_y1"),
	basesY2: text("bases_y2"),
	positionsX0: text("positions_x0"),
	positionsX1: text("positions_x1"),
	positionsX2: text("positions_x2"),
	positionsX3: text("positions_x3"),
	positionsX4: text("positions_x4"),
	positionsX5: text("positions_x5"),
	positionsX6: text("positions_x6"),
	positionsX7: text("positions_x7"),
	positionsX8: text("positions_x8"),
	positionsX9: text("positions_x9"),
	positionsY0: text("positions_y0"),
	positionsY1: text("positions_y1"),
	positionsY2: text("positions_y2"),
	positionsY3: text("positions_y3"),
	positionsY4: text("positions_y4"),
	positionsY5: text("positions_y5"),
	positionsY6: text("positions_y6"),
	positionsY7: text("positions_y7"),
	positionsY8: text("positions_y8"),
	positionsY9: text("positions_y9"),
	avg: text("avg"),
	avgL: text("avg_l"),
	avgR: text("avg_r"),
	d: text("d"),
	t: text("t"),
	hr: text("hr"),
	hrR: text("hr_r"),
	hrL: text("hr_l"),
	temperature0: text("temperature0"),
	temperature1: text("temperature1"),
	temperature2: text("temperature2"),
	temperature3: text("temperature3"),
	temperature4: text("temperature4"),
	temperature5: text("temperature5"),
	temperature6: text("temperature6"),
	temperature7: text("temperature7"),
	temperature8: text("temperature8"),
	temperature9: text("temperature9"),
	temperature10: text("temperature10"),
	temperature11: text("temperature11"),
	rain0: text("rain0"),
	rain1: text("rain1"),
	rain2: text("rain2"),
	rain3: text("rain3"),
	rain4: text("rain4"),
	rain5: text("rain5"),
	rain6: text("rain6"),
	rain7: text("rain7"),
	rain8: text("rain8"),
	rain9: text("rain9"),
	rain10: text("rain10"),
	rain11: text("rain11"),
	wind: text("wind"),
	windDirection: text("wind_direction"),
	distances0: text("distances0"),
	distances1: text("distances1"),
	distances2: text("distances2"),
	distances3: text("distances3"),
	distances4: text("distances4"),
	distances5: text("distances5"),
	distances6: text("distances6"),
	wallHeights0: text("wall_heights0"),
	wallHeights1: text("wall_heights1"),
	wallHeights2: text("wall_heights2"),
	wallHeights3: text("wall_heights3"),
	wallHeights4: text("wall_heights4"),
	wallHeights5: text("wall_heights5"),
	wallHeights6: text("wall_heights6"),
	name: text("name"),
	picture: text("picture"),
	pictureNight: text("picture_night"),
	nationId: text("nation_id"),
	capacity: text("capacity"),
	type: text("type"),
	foulGround: text("foul_ground"),
	turf: text("turf"),
	gender: text("gender"),
	modelFolder: text("model_folder"),
	fileName3DModel: text("file_name_3d_model"),
	homeTeamDugoutIsAtFirstBase: text("home_team_dugout_is_at_first_base"),
});

export const playersAtBatBattingStats = sqliteTable("players_at_bat_batting_stats", {
	playerId: text("player_id"),
	gameId: text("game_id"),
	opponentPlayerId: text("opponent_player_id"),
	teamId: text("team_id"),
	sac: text("sac"),
	balls: text("balls"),
	strikes: text("strikes"),
	result: text("result"),
	base1: text("base1"),
	base2: text("base2"),
	base3: text("base3"),
	close: text("Close"),
	pinch: text("pinch"),
	inning: text("inning"),
	runDiff: text("run_diff"),
	outs: text("outs"),
	sb: text("sb"),
	cs: text("cs"),
	rbi: text("rbi"),
	r: text("r"),
	spot: text("spot"),
	hitLoc: text("hit_loc"),
	hitXy: text("hit_xy"),
	exitVelo: text("exit_velo"),
	launchAngle: text("launch_angle"),
});

export const playersAwards = sqliteTable("players_awards", {
	playerId: text("player_id"),
	leagueId: text("league_id"),
	teamId: text("team_id"),
	subLeagueId: text("sub_league_id"),
	awardId: text("award_id"),
	year: text("year"),
	season: text("season"),
	position: text("position"),
	day: text("day"),
	month: text("month"),
	finish: text("finish"),
});
*/

export const playersBatting = sqliteTable("players_batting", {
  player_id: integer("player_id"),
  team_id: integer("team_id"),
  league_id: integer("league_id"),
  position: integer("position"),
  role: integer("role"),
  batting_ratings_overall_contact: integer("batting_ratings_overall_contact"),
  batting_ratings_overall_gap: integer("batting_ratings_overall_gap"),
  batting_ratings_overall_eye: integer("batting_ratings_overall_eye"),
  batting_ratings_overall_strikeouts: integer(
    "batting_ratings_overall_strikeouts",
  ),
  batting_ratings_overall_hp: integer("batting_ratings_overall_hp"),
  batting_ratings_overall_power: integer("batting_ratings_overall_power"),
  batting_ratings_overall_babip: integer("batting_ratings_overall_babip"),
  batting_ratings_vsr_contact: integer("batting_ratings_vsr_contact"),
  batting_ratings_vsr_gap: integer("batting_ratings_vsr_gap"),
  batting_ratings_vsr_eye: integer("batting_ratings_vsr_eye"),
  batting_ratings_vsr_strikeouts: integer("batting_ratings_vsr_strikeouts"),
  batting_ratings_vsr_hp: integer("batting_ratings_vsr_hp"),
  batting_ratings_vsr_power: integer("batting_ratings_vsr_power"),
  batting_ratings_vsr_babip: integer("batting_ratings_vsr_babip"),
  batting_ratings_vsl_contact: integer("batting_ratings_vsl_contact"),
  batting_ratings_vsl_gap: integer("batting_ratings_vsl_gap"),
  batting_ratings_vsl_eye: integer("batting_ratings_vsl_eye"),
  batting_ratings_vsl_strikeouts: integer("batting_ratings_vsl_strikeouts"),
  batting_ratings_vsl_hp: integer("batting_ratings_vsl_hp"),
  batting_ratings_vsl_power: integer("batting_ratings_vsl_power"),
  batting_ratings_vsl_babip: integer("batting_ratings_vsl_babip"),
  batting_ratings_talent_contact: integer("batting_ratings_talent_contact"),
  batting_ratings_talent_gap: integer("batting_ratings_talent_gap"),
  batting_ratings_talent_eye: integer("batting_ratings_talent_eye"),
  batting_ratings_talent_strikeouts: integer(
    "batting_ratings_talent_strikeouts",
  ),
  batting_ratings_talent_hp: integer("batting_ratings_talent_hp"),
  batting_ratings_talent_power: integer("batting_ratings_talent_power"),
  batting_ratings_talent_babip: integer("batting_ratings_talent_babip"),
  batting_ratings_misc_bunt: integer("batting_ratings_misc_bunt"),
  batting_ratings_misc_bunt_for_hit: integer(
    "batting_ratings_misc_bunt_for_hit",
  ),
  batting_ratings_misc_gb_hitter_type: integer(
    "batting_ratings_misc_gb_hitter_type",
  ),
  batting_ratings_misc_fb_hitter_type: integer(
    "batting_ratings_misc_fb_hitter_type",
  ),
}, (table) => {
  return {
    batting_rating_player_id_idx: uniqueIndex("batting_rating_player_id_idx")
      .on(table.player_id),
    batting_rating_team_id_idx: index("batting_rating_team_id_idx").on(
      table.team_id,
    ),
  };
});
/*
export const playersCareerBattingStats = sqliteTable("players_career_batting_stats", {
	playerId: text("player_id"),
	year: text("year"),
	teamId: text("team_id"),
	gameId: text("game_id"),
	leagueId: text("league_id"),
	levelId: text("level_id"),
	splitId: text("split_id"),
	position: text("position"),
	ab: text("ab"),
	h: text("h"),
	k: text("k"),
	pa: text("pa"),
	pitchesSeen: text("pitches_seen"),
	g: text("g"),
	gs: text("gs"),
	d: text("d"),
	t: text("t"),
	hr: text("hr"),
	r: text("r"),
	rbi: text("rbi"),
	sb: text("sb"),
	cs: text("cs"),
	bb: text("bb"),
	ibb: text("ibb"),
	gdp: text("gdp"),
	sh: text("sh"),
	sf: text("sf"),
	hp: text("hp"),
	ci: text("ci"),
	wpa: text("wpa"),
	stint: text("stint"),
	ubr: text("ubr"),
	war: text("war"),
});

export const playersCareerFieldingStats = sqliteTable("players_career_fielding_stats", {
	playerId: text("player_id"),
	year: text("year"),
	teamId: text("team_id"),
	leagueId: text("league_id"),
	levelId: text("level_id"),
	splitId: text("split_id"),
	position: text("position"),
	tc: text("tc"),
	a: text("a"),
	po: text("po"),
	er: text("er"),
	ip: text("ip"),
	g: text("g"),
	gs: text("gs"),
	e: text("e"),
	dp: text("dp"),
	tp: text("tp"),
	pb: text("pb"),
	sba: text("sba"),
	rto: text("rto"),
	ipf: text("ipf"),
	plays: text("plays"),
	playsBase: text("plays_base"),
	roe: text("roe"),
	opps0: text("opps_0"),
	oppsMade0: text("opps_made_0"),
	opps1: text("opps_1"),
	oppsMade1: text("opps_made_1"),
	opps2: text("opps_2"),
	oppsMade2: text("opps_made_2"),
	opps3: text("opps_3"),
	oppsMade3: text("opps_made_3"),
	opps4: text("opps_4"),
	oppsMade4: text("opps_made_4"),
	opps5: text("opps_5"),
	oppsMade5: text("opps_made_5"),
	framing: text("framing"),
	arm: text("arm"),
	zr: text("zr"),
});

export const playersCareerPitchingStats = sqliteTable("players_career_pitching_stats", {
	playerId: text("player_id"),
	year: text("year"),
	teamId: text("team_id"),
	gameId: text("game_id"),
	leagueId: text("league_id"),
	levelId: text("level_id"),
	splitId: text("split_id"),
	ip: text("ip"),
	ab: text("ab"),
	tb: text("tb"),
	ha: text("ha"),
	k: text("k"),
	bf: text("bf"),
	rs: text("rs"),
	bb: text("bb"),
	r: text("r"),
	er: text("er"),
	gb: text("gb"),
	fb: text("fb"),
	pi: text("pi"),
	ipf: text("ipf"),
	g: text("g"),
	gs: text("gs"),
	w: text("w"),
	l: text("l"),
	s: text("s"),
	sa: text("sa"),
	da: text("da"),
	sh: text("sh"),
	sf: text("sf"),
	ta: text("ta"),
	hra: text("hra"),
	bk: text("bk"),
	ci: text("ci"),
	iw: text("iw"),
	wp: text("wp"),
	hp: text("hp"),
	gf: text("gf"),
	dp: text("dp"),
	qs: text("qs"),
	svo: text("svo"),
	bs: text("bs"),
	ra: text("ra"),
	cg: text("cg"),
	sho: text("sho"),
	sb: text("sb"),
	cs: text("cs"),
	hld: text("hld"),
	ir: text("ir"),
	irs: text("irs"),
	wpa: text("wpa"),
	li: text("li"),
	stint: text("stint"),
	outs: text("outs"),
	sd: text("sd"),
	md: text("md"),
	war: text("war"),
	ra9War: text("ra9war"),
});

export const playersContract = sqliteTable("players_contract", {
	playerId: integer("player_id"),
	teamId: integer("team_id"),
	leagueId: integer("league_id"),
	position: integer("position"),
	role: integer("role"),
	isMajor: integer("is_major"),
	noTrade: integer("no_trade"),
	lastYearTeamOption: integer("last_year_team_option"),
	lastYearPlayerOption: integer("last_year_player_option"),
	lastYearVestingOption: integer("last_year_vesting_option"),
	nextLastYearTeamOption: integer("next_last_year_team_option"),
	nextLastYearPlayerOption: integer("next_last_year_player_option"),
	nextLastYearVestingOption: integer("next_last_year_vesting_option"),
	contractTeamId: integer("contract_team_id"),
	contractLeagueId: integer("contract_league_id"),
	seasonYear: integer("season_year"),
	salary0: integer("salary0"),
	salary1: integer("salary1"),
	salary2: integer("salary2"),
	salary3: integer("salary3"),
	salary4: integer("salary4"),
	salary5: integer("salary5"),
	salary6: integer("salary6"),
	salary7: integer("salary7"),
	salary8: integer("salary8"),
	salary9: integer("salary9"),
	salary10: integer("salary10"),
	salary11: integer("salary11"),
	salary12: integer("salary12"),
	salary13: integer("salary13"),
	salary14: integer("salary14"),
	years: integer("years"),
	currentYear: integer("current_year"),
	minimumPa: integer("minimum_pa"),
	minimumPaBonus: integer("minimum_pa_bonus"),
	minimumIp: integer("minimum_ip"),
	minimumIpBonus: integer("minimum_ip_bonus"),
	mvpBonus: integer("mvp_bonus"),
	cyyoungBonus: integer("cyyoung_bonus"),
	allstarBonus: integer("allstar_bonus"),
	nextLastYearOptionBuyout: integer("next_last_year_option_buyout"),
	lastYearOptionBuyout: integer("last_year_option_buyout"),
	optOut: integer("opt_out"),
	optOutRelegation: integer("opt_out_relegation"),
	retained: integer("retained"),
});

export const playersContractExtension = sqliteTable("players_contract_extension", {
	playerId: text("player_id"),
	teamId: text("team_id"),
	leagueId: text("league_id"),
	position: text("position"),
	role: text("role"),
	isMajor: text("is_major"),
	noTrade: text("no_trade"),
	lastYearTeamOption: text("last_year_team_option"),
	lastYearPlayerOption: text("last_year_player_option"),
	lastYearVestingOption: text("last_year_vesting_option"),
	nextLastYearTeamOption: text("next_last_year_team_option"),
	nextLastYearPlayerOption: text("next_last_year_player_option"),
	nextLastYearVestingOption: text("next_last_year_vesting_option"),
	contractTeamId: text("contract_team_id"),
	contractLeagueId: text("contract_league_id"),
	seasonYear: text("season_year"),
	salary0: text("salary0"),
	salary1: text("salary1"),
	salary2: text("salary2"),
	salary3: text("salary3"),
	salary4: text("salary4"),
	salary5: text("salary5"),
	salary6: text("salary6"),
	salary7: text("salary7"),
	salary8: text("salary8"),
	salary9: text("salary9"),
	salary10: text("salary10"),
	salary11: text("salary11"),
	salary12: text("salary12"),
	salary13: text("salary13"),
	salary14: text("salary14"),
	years: text("years"),
	currentYear: text("current_year"),
	minimumPa: text("minimum_pa"),
	minimumPaBonus: text("minimum_pa_bonus"),
	minimumIp: text("minimum_ip"),
	minimumIpBonus: text("minimum_ip_bonus"),
	mvpBonus: text("mvp_bonus"),
	cyyoungBonus: text("cyyoung_bonus"),
	allstarBonus: text("allstar_bonus"),
	nextLastYearOptionBuyout: text("next_last_year_option_buyout"),
	lastYearOptionBuyout: text("last_year_option_buyout"),
	optOut: text("opt_out"),
	optOutRelegation: text("opt_out_relegation"),
});
*/
export const playersFielding = sqliteTable("players_fielding", {
  player_id: integer("player_id"),
  team_id: integer("team_id"),
  league_id: integer("league_id"),
  position: integer("position"),
  role: integer("role"),
  fielding_ratings_infield_range: integer("fielding_ratings_infield_range"),
  fielding_ratings_infield_arm: integer("fielding_ratings_infield_arm"),
  fielding_ratings_turn_doubleplay: integer("fielding_ratings_turn_doubleplay"),
  fielding_ratings_outfield_range: integer("fielding_ratings_outfield_range"),
  fielding_ratings_outfield_arm: integer("fielding_ratings_outfield_arm"),
  fielding_ratings_catcher_arm: integer("fielding_ratings_catcher_arm"),
  fielding_ratings_catcher_ability: integer("fielding_ratings_catcher_ability"),
  fielding_ratings_infield_error: integer("fielding_ratings_infield_error"),
  fielding_ratings_outfield_error: integer("fielding_ratings_outfield_error"),
  fielding_experience0: integer("fielding_experience0"),
  fielding_experience1: integer("fielding_experience1"),
  fielding_experience2: integer("fielding_experience2"),
  fielding_experience3: integer("fielding_experience3"),
  fielding_experience4: integer("fielding_experience4"),
  fielding_experience5: integer("fielding_experience5"),
  fielding_experience6: integer("fielding_experience6"),
  fielding_experience7: integer("fielding_experience7"),
  fielding_experience8: integer("fielding_experience8"),
  fielding_experience9: integer("fielding_experience9"),
  fielding_rating_pos1: integer("fielding_rating_pos1"),
  fielding_rating_pos2: integer("fielding_rating_pos2"),
  fielding_rating_pos3: integer("fielding_rating_pos3"),
  fielding_rating_pos4: integer("fielding_rating_pos4"),
  fielding_rating_pos5: integer("fielding_rating_pos5"),
  fielding_rating_pos6: integer("fielding_rating_pos6"),
  fielding_rating_pos7: integer("fielding_rating_pos7"),
  fielding_rating_pos8: integer("fielding_rating_pos8"),
  fielding_rating_pos9: integer("fielding_rating_pos9"),
});
/*
export const playersGameBatting = sqliteTable("players_game_batting", {
	playerId: text("player_id"),
	year: text("year"),
	teamId: text("team_id"),
	gameId: text("game_id"),
	leagueId: text("league_id"),
	levelId: text("level_id"),
	splitId: text("split_id"),
	position: text("position"),
	ab: text("ab"),
	h: text("h"),
	k: text("k"),
	pa: text("pa"),
	pitchesSeen: text("pitches_seen"),
	g: text("g"),
	gs: text("gs"),
	d: text("d"),
	t: text("t"),
	hr: text("hr"),
	r: text("r"),
	rbi: text("rbi"),
	sb: text("sb"),
	cs: text("cs"),
	bb: text("bb"),
	ibb: text("ibb"),
	gdp: text("gdp"),
	sh: text("sh"),
	sf: text("sf"),
	hp: text("hp"),
	ci: text("ci"),
	wpa: text("wpa"),
	stint: text("stint"),
	ubr: text("ubr"),
});

export const playersGamePitchingStats = sqliteTable("players_game_pitching_stats", {
	playerId: text("player_id"),
	year: text("year"),
	teamId: text("team_id"),
	gameId: text("game_id"),
	leagueId: text("league_id"),
	levelId: text("level_id"),
	splitId: text("split_id"),
	ip: text("ip"),
	ab: text("ab"),
	tb: text("tb"),
	ha: text("ha"),
	k: text("k"),
	bf: text("bf"),
	rs: text("rs"),
	bb: text("bb"),
	r: text("r"),
	er: text("er"),
	gb: text("gb"),
	fb: text("fb"),
	pi: text("pi"),
	ipf: text("ipf"),
	g: text("g"),
	gs: text("gs"),
	w: text("w"),
	l: text("l"),
	s: text("s"),
	sa: text("sa"),
	da: text("da"),
	sh: text("sh"),
	sf: text("sf"),
	ta: text("ta"),
	hra: text("hra"),
	bk: text("bk"),
	ci: text("ci"),
	iw: text("iw"),
	wp: text("wp"),
	hp: text("hp"),
	gf: text("gf"),
	dp: text("dp"),
	qs: text("qs"),
	svo: text("svo"),
	bs: text("bs"),
	ra: text("ra"),
	cg: text("cg"),
	sho: text("sho"),
	sb: text("sb"),
	cs: text("cs"),
	hld: text("hld"),
	ir: text("ir"),
	irs: text("irs"),
	wpa: text("wpa"),
	li: text("li"),
	stint: text("stint"),
	outs: text("outs"),
	sd: text("sd"),
	md: text("md"),
});

export const playersIndividualBattingStats = sqliteTable("players_individual_batting_stats", {
	playerId: text("player_id"),
	opponentId: text("opponent_id"),
	ab: text("ab"),
	h: text("h"),
	hr: text("hr"),
});

export const playersInjuryHistory = sqliteTable("players_injury_history", {
	playerId: text("player_id"),
	date: text("date"),
	length: text("length"),
	setbacks: text("setbacks"),
	dayToDay: text("day_to_day"),
	effect: text("effect"),
	bodyPart: text("body_part"),
});

export const playersLeagueLeader = sqliteTable("players_league_leader", {
	playerId: text("player_id"),
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	year: text("year"),
	category: text("category"),
	place: text("place"),
	amount: text("amount"),
});
*/
export const playersPitching = sqliteTable("players_pitching", {
  player_id: integer("player_id"),
  team_id: integer("team_id"),
  league_id: integer("league_id"),
  position: integer("position"),
  role: integer("role"),
  pitching_ratings_overall_stuff: integer("pitching_ratings_overall_stuff"),
  pitching_ratings_overall_control: integer("pitching_ratings_overall_control"),
  pitching_ratings_overall_movement: integer(
    "pitching_ratings_overall_movement",
  ),
  pitching_ratings_overall_balk: integer("pitching_ratings_overall_balk"),
  pitching_ratings_overall_hp: integer("pitching_ratings_overall_hp"),
  pitching_ratings_overall_wild_pitch: integer(
    "pitching_ratings_overall_wild_pitch",
  ),
  pitching_ratings_vsr_stuff: integer("pitching_ratings_vsr_stuff"),
  pitching_ratings_vsr_control: integer("pitching_ratings_vsr_control"),
  pitching_ratings_vsr_movement: integer("pitching_ratings_vsr_movement"),
  pitching_ratings_vsr_balk: integer("pitching_ratings_vsr_balk"),
  pitching_ratings_vsr_hp: integer("pitching_ratings_vsr_hp"),
  pitching_ratings_vsr_wild_pitch: integer("pitching_ratings_vsr_wild_pitch"),
  pitching_ratings_vsl_stuff: integer("pitching_ratings_vsl_stuff"),
  pitching_ratings_vsl_control: integer("pitching_ratings_vsl_control"),
  pitching_ratings_vsl_movement: integer("pitching_ratings_vsl_movement"),
  pitching_ratings_vsl_balk: integer("pitching_ratings_vsl_balk"),
  pitching_ratings_vsl_hp: integer("pitching_ratings_vsl_hp"),
  pitching_ratings_vsl_wild_pitch: integer("pitching_ratings_vsl_wild_pitch"),
  pitching_ratings_talent_stuff: integer("pitching_ratings_talent_stuff"),
  pitching_ratings_talent_control: integer("pitching_ratings_talent_control"),
  pitching_ratings_talent_movement: integer("pitching_ratings_talent_movement"),
  pitching_ratings_talent_balk: integer("pitching_ratings_talent_balk"),
  pitching_ratings_talent_hp: integer("pitching_ratings_talent_hp"),
  pitching_ratings_talent_wild_pitch: integer(
    "pitching_ratings_talent_wild_pitch",
  ),
  pitching_ratings_pitches_fastball: integer(
    "pitching_ratings_pitches_fastball",
  ),
  pitching_ratings_pitches_slider: integer("pitching_ratings_pitches_slider"),
  pitching_ratings_pitches_curveball: integer(
    "pitching_ratings_pitches_curveball",
  ),
  pitching_ratings_pitches_screwball: integer(
    "pitching_ratings_pitches_screwball",
  ),
  pitching_ratings_pitches_forkball: integer(
    "pitching_ratings_pitches_forkball",
  ),
  pitching_ratings_pitches_changeup: integer(
    "pitching_ratings_pitches_changeup",
  ),
  pitching_ratings_pitches_sinker: integer("pitching_ratings_pitches_sinker"),
  pitching_ratings_pitches_splitter: integer(
    "pitching_ratings_pitches_splitter",
  ),
  pitching_ratings_pitches_knuckleball: integer(
    "pitching_ratings_pitches_knuckleball",
  ),
  pitching_ratings_pitches_cutter: integer("pitching_ratings_pitches_cutter"),
  pitching_ratings_pitches_circlechange: integer(
    "pitching_ratings_pitches_circlechange",
  ),
  pitching_ratings_pitches_knucklecurve: integer(
    "pitching_ratings_pitches_knucklecurve",
  ),
  pitching_ratings_pitches_talent_fastball: integer(
    "pitching_ratings_pitches_talent_fastball",
  ),
  pitching_ratings_pitches_talent_slider: integer(
    "pitching_ratings_pitches_talent_slider",
  ),
  pitching_ratings_pitches_talent_curveball: integer(
    "pitching_ratings_pitches_talent_curveball",
  ),
  pitching_ratings_pitches_talent_screwball: integer(
    "pitching_ratings_pitches_talent_screwball",
  ),
  pitching_ratings_pitches_talent_forkball: integer(
    "pitching_ratings_pitches_talent_forkball",
  ),
  pitching_ratings_pitches_talent_changeup: integer(
    "pitching_ratings_pitches_talent_changeup",
  ),
  pitching_ratings_pitches_talent_sinker: integer(
    "pitching_ratings_pitches_talent_sinker",
  ),
  pitching_ratings_pitches_talent_splitter: integer(
    "pitching_ratings_pitches_talent_splitter",
  ),
  pitching_ratings_pitches_talent_knuckleball: integer(
    "pitching_ratings_pitches_talent_knuckleball",
  ),
  pitching_ratings_pitches_talent_cutter: integer(
    "pitching_ratings_pitches_talent_cutter",
  ),
  pitching_ratings_pitches_talent_circlechange: integer(
    "pitching_ratings_pitches_talent_circlechange",
  ),
  pitching_ratings_pitches_talent_knucklecurve: integer(
    "pitching_ratings_pitches_talent_knucklecurve",
  ),
  pitching_ratings_misc_velocity: integer("pitching_ratings_misc_velocity"),
  pitching_ratings_misc_arm_slot: integer("pitching_ratings_misc_arm_slot"),
  pitching_ratings_misc_stamina: integer("pitching_ratings_misc_stamina"),
  pitching_ratings_misc_ground_fly: integer("pitching_ratings_misc_ground_fly"),
  pitching_ratings_misc_hold: integer("pitching_ratings_misc_hold"),
  pitching_ratings_babip: integer("pitching_ratings_babip"),
}, (table) => {
  return {
    pitching_rating_player_id_idx: uniqueIndex("pitching_rating_player_id_idx")
      .on(table.player_id),
    pitching_rating_team_id_idx: index("pitching_rating_team_id_idx").on(
      table.team_id,
    ),
  };
});
/*

export const playersRosterStatus = sqliteTable("players_roster_status", {
	playerId: integer("player_id"),
	teamId: integer("team_id"),
	leagueId: integer("league_id"),
	position: integer("position"),
	role: integer("role"),
	playingLevel: integer("playing_level"),
	isActive: integer("is_active"),
	isOnSecondary: integer("is_on_secondary"),
	isOnDl: integer("is_on_dl"),
	isOnDl60: integer("is_on_dl60"),
	mustBeActive: integer("must_be_active"),
	justSigned: integer("just_signed"),
	wasOnActive: integer("was_on_active"),
	wasOnSecondary: integer("was_on_secondary"),
	wasOnDl: integer("was_on_dl"),
	mlbServiceYears: integer("mlb_service_years"),
	secondaryServiceYears: integer("secondary_service_years"),
	proServiceYears: integer("pro_service_years"),
	mlbServiceDays: integer("mlb_service_days"),
	secondaryServiceDays: integer("secondary_service_days"),
	proServiceDays: integer("pro_service_days"),
	mlbServiceDaysThisYear: integer("mlb_service_days_this_year"),
	secondaryServiceDaysThisYear: integer("secondary_service_days_this_year"),
	proServiceDaysThisYear: integer("pro_service_days_this_year"),
	dlDaysThisYear: integer("dl_days_this_year"),
	yearsProtectedFromRule5: integer("years_protected_from_rule_5"),
	isOnWaivers: integer("is_on_waivers"),
	designatedForAssignment: integer("designated_for_assignment"),
	irrevocableWaivers: integer("irrevocable_waivers"),
	daysOnWaivers: integer("days_on_waivers"),
	daysOnWaiversLeft: integer("days_on_waivers_left"),
	daysOnDfaLeft: integer("days_on_dfa_left"),
	claimedTeamId: integer("claimed_team_id"),
	optionsUsed: integer("options_used"),
	optionsUsedThisYear: integer("options_used_this_year"),
	hasReceivedArbitration: integer("has_received_arbitration"),
	wasTraded: integer("was_traded"),
	tradeStatus: integer("trade_status"),
});

export const playersSalaryHistory = sqliteTable("players_salary_history", {
	playerId: text("player_id"),
	teamId: text("team_id"),
	year: text("year"),
	salary: text("salary"),
	uniform: text("uniform"),
});

export const playersStreak = sqliteTable("players_streak", {
	playerId: text("player_id"),
	leagueId: text("league_id"),
	streakId: text("streak_id"),
	value: text("value"),
	hasEnded: text("has_ended"),
	started: text("started"),
	ended: text("ended"),
});

export const playersValue = sqliteTable("players_value", {
	playerId: text("player_id"),
	teamId: text("team_id"),
	leagueId: text("league_id"),
	position: text("position"),
	role: text("role"),
	offensiveValue: text("offensive_value"),
	offensiveValueTalent: text("offensive_value_talent"),
	offensiveValueVsl: text("offensive_value_vsl"),
	offensiveValueVsr: text("offensive_value_vsr"),
	pitchingValue: text("pitching_value"),
	pitchingValueTalent: text("pitching_value_talent"),
	pitchingValueVsl: text("pitching_value_vsl"),
	pitchingValueVsr: text("pitching_value_vsr"),
	overallValue: text("overall_value"),
	talentValue: text("talent_value"),
	careerValue: text("career_value"),
	leadoffValueVsl: text("leadoff_value_vsl"),
	leadoffValueVsr: text("leadoff_value_vsr"),
	runningValue: text("running_value"),
	stealingValue: text("stealing_value"),
	seasonPerformance: text("season_performance"),
	statsValue0: text("stats_value_0"),
	statsValue1: text("stats_value_1"),
	statsValue2: text("stats_value_2"),
	statsMod0: text("stats_mod_0"),
	statsMod1: text("stats_mod_1"),
	statsMod2: text("stats_mod_2"),
	ratingsValue: text("ratings_value"),
	overallSp: text("overall_sp"),
	overallRp: text("overall_rp"),
	overallC: text("overall_c"),
	overall1B: text("overall_1b"),
	overall2B: text("overall_2b"),
	overall3B: text("overall_3b"),
	overallSs: text("overall_ss"),
	overallLf: text("overall_lf"),
	overallCf: text("overall_cf"),
	overallRf: text("overall_rf"),
	awardBat: text("award_bat"),
	awardPit: text("award_pit"),
	awardField: text("award_field"),
	oa: text("oa"),
	pot: text("pot"),
});

export const projectedStartingPitchers = sqliteTable("projected_starting_pitchers", {
	teamId: text("team_id"),
	starter0: text("starter_0"),
	starter1: text("starter_1"),
	starter2: text("starter_2"),
	starter3: text("starter_3"),
	starter4: text("starter_4"),
	starter5: text("starter_5"),
	starter6: text("starter_6"),
	starter7: text("starter_7"),
});

export const states = sqliteTable("states", {
	stateId: text("state_id"),
	nationId: text("nation_id"),
	name: text("name"),
	abbreviation: text("abbreviation"),
	population: text("population"),
	mainLanguageId: text("main_language_id"),
});

export const subLeagues = sqliteTable("sub_leagues", {
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	name: text("name"),
	abbr: text("abbr"),
	gender: text("gender"),
	designatedHitter: text("designated_hitter"),
});

export const teamAffiliations = sqliteTable("team_affiliations", {
	teamId: text("team_id"),
	affiliatedTeamId: text("affiliated_team_id"),
});

export const teamBattingStats = sqliteTable("team_batting_stats", {
	teamId: text("team_id"),
	year: text("year"),
	leagueId: text("league_id"),
	levelId: text("level_id"),
	splitId: text("split_id"),
	pa: text("pa"),
	ab: text("ab"),
	h: text("h"),
	k: text("k"),
	tb: text("tb"),
	s: text("s"),
	d: text("d"),
	t: text("t"),
	hr: text("hr"),
	sb: text("sb"),
	cs: text("cs"),
	rbi: text("rbi"),
	r: text("r"),
	bb: text("bb"),
	ibb: text("ibb"),
	hp: text("hp"),
	sh: text("sh"),
	sf: text("sf"),
	ci: text("ci"),
	gdp: text("gdp"),
	g: text("g"),
	gs: text("gs"),
	ebh: text("ebh"),
	pitchesSeen: text("pitches_seen"),
	avg: text("avg"),
	obp: text("obp"),
	slg: text("slg"),
	rc: text("rc"),
	rc27: text("rc27"),
	iso: text("iso"),
	woba: text("woba"),
	ops: text("ops"),
	sbp: text("sbp"),
});

export const teamBullpenPitchingStats = sqliteTable("team_bullpen_pitching_stats", {
	teamId: text("team_id"),
	year: text("year"),
	leagueId: text("league_id"),
	levelId: text("level_id"),
	splitId: text("split_id"),
	ab: text("ab"),
	ip: text("ip"),
	bf: text("bf"),
	tb: text("tb"),
	ha: text("ha"),
	k: text("k"),
	rs: text("rs"),
	bb: text("bb"),
	r: text("r"),
	er: text("er"),
	gb: text("gb"),
	fb: text("fb"),
	pi: text("pi"),
	ipf: text("ipf"),
	g: text("g"),
	gs: text("gs"),
	w: text("w"),
	l: text("l"),
	s: text("s"),
	sa: text("sa"),
	da: text("da"),
	sh: text("sh"),
	sf: text("sf"),
	ta: text("ta"),
	hra: text("hra"),
	bk: text("bk"),
	ci: text("ci"),
	iw: text("iw"),
	wp: text("wp"),
	hp: text("hp"),
	gf: text("gf"),
	dp: text("dp"),
	qs: text("qs"),
	svo: text("svo"),
	bs: text("bs"),
	ra: text("ra"),
	cg: text("cg"),
	sho: text("sho"),
	sb: text("sb"),
	cs: text("cs"),
	hld: text("hld"),
	r9: text("r9"),
	avg: text("avg"),
	obp: text("obp"),
	slg: text("slg"),
	ops: text("ops"),
	h9: text("h9"),
	k9: text("k9"),
	hr9: text("hr9"),
	bb9: text("bb9"),
	cgp: text("cgp"),
	fip: text("fip"),
	qsp: text("qsp"),
	winp: text("winp"),
	rsg: text("rsg"),
	svp: text("svp"),
	bsvp: text("bsvp"),
	gfp: text("gfp"),
	era: text("era"),
	pig: text("pig"),
	ws: text("ws"),
	whip: text("whip"),
	gbfbp: text("gbfbp"),
	kbb: text("kbb"),
	babip: text("babip"),
});

export const teamFieldingStatsStats = sqliteTable("team_fielding_stats_stats", {
	teamId: text("team_id"),
	year: text("year"),
	leagueId: text("league_id"),
	levelId: text("level_id"),
	splitId: text("split_id"),
	position: text("position"),
	g: text("g"),
	gs: text("gs"),
	tc: text("tc"),
	a: text("a"),
	po: text("po"),
	e: text("e"),
	dp: text("dp"),
	tp: text("tp"),
	pb: text("pb"),
	sba: text("sba"),
	rto: text("rto"),
	er: text("er"),
	ip: text("ip"),
	ipf: text("ipf"),
	pct: text("pct"),
	range: text("range"),
	rtop: text("rtop"),
	cera: text("cera"),
});

export const teamFinancials = sqliteTable("team_financials", {
	teamId: text("team_id"),
	gateRevenue: text("gate_revenue"),
	gateShareGained: text("gate_share_gained"),
	gateShareLost: text("gate_share_lost"),
	seasonTicketRevenue: text("season_ticket_revenue"),
	mediaRevenue: text("media_revenue"),
	merchandisingRevenue: text("merchandising_revenue"),
	revenueSharing: text("revenue_sharing"),
	luxurySharing: text("luxury_sharing"),
	playoffRevenue: text("playoff_revenue"),
	cash: text("cash"),
	cashOwner: text("cash_owner"),
	cashTrades: text("cash_trades"),
	previousBalance: text("previous_balance"),
	playerExpenses: text("player_expenses"),
	staffExpenses: text("staff_expenses"),
	stadiumExpenses: text("stadium_expenses"),
	seasonTickets: text("season_tickets"),
	attendance: text("attendance"),
	fanInterest: text("fan_interest"),
	fanLoyalty: text("fan_loyalty"),
	fanModifier: text("fan_modifier"),
	ticketPrice: text("ticket_price"),
	localMediaContract: text("local_media_contract"),
	localMediaContractExpires: text("local_media_contract_expires"),
	nationalMediaContract: text("national_media_contract"),
	nationalMediaContractExpires: text("national_media_contract_expires"),
	scoutingBudget: text("scouting_budget"),
	developmentBudget: text("development_budget"),
	draftBudget: text("draft_budget"),
	draftExpenses: text("draft_expenses"),
	intlFaBudget: text("intl_fa_budget"),
	spentInIntl: text("spent_in_intl"),
	budget: text("budget"),
	market: text("market"),
	ownerExpectation: text("owner_expectation"),
	totalRevenue: text("total_revenue"),
	totalExpenses: text("total_expenses"),
	financialBalance: text("financial_balance"),
	budgetBalance: text("budget_balance"),
	playerPayroll: text("player_payroll"),
	playerPayrollNextSeason: text("player_payroll_next_season"),
	playerPayrollOffered: text("player_payroll_offered"),
	mode: text("mode"),
	cashTradesAvailable: text("cash_trades_available"),
});

export const teamHistory = sqliteTable("team_history", {
	teamId: text("team_id"),
	year: text("year"),
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	divisionId: text("division_id"),
	name: text("name"),
	abbr: text("abbr"),
	nickname: text("nickname"),
	bestHitterId: text("best_hitter_id"),
	bestPitcherId: text("best_pitcher_id"),
	bestRookieId: text("best_rookie_id"),
	managerId: text("manager_id"),
	madePlayoffs: text("made_playoffs"),
	wonPlayoffs: text("won_playoffs"),
	fired: text("fired"),
	positionInDivision: text("position_in_division"),
});

export const teamHistoryBattingStats = sqliteTable("team_history_batting_stats", {
	teamId: text("team_id"),
	year: text("year"),
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	divisionId: text("division_id"),
	levelId: text("level_id"),
	splitId: text("split_id"),
	pa: text("pa"),
	ab: text("ab"),
	h: text("h"),
	k: text("k"),
	tb: text("tb"),
	s: text("s"),
	d: text("d"),
	t: text("t"),
	hr: text("hr"),
	sb: text("sb"),
	cs: text("cs"),
	rbi: text("rbi"),
	r: text("r"),
	bb: text("bb"),
	ibb: text("ibb"),
	hp: text("hp"),
	sh: text("sh"),
	sf: text("sf"),
	ci: text("ci"),
	gdp: text("gdp"),
	g: text("g"),
	gs: text("gs"),
	ebh: text("ebh"),
	pitchesSeen: text("pitches_seen"),
	avg: text("avg"),
	obp: text("obp"),
	slg: text("slg"),
	rc: text("rc"),
	rc27: text("rc27"),
	iso: text("iso"),
	woba: text("woba"),
	ops: text("ops"),
	sbp: text("sbp"),
});

export const teamHistoryFieldingStatsStats = sqliteTable("team_history_fielding_stats_stats", {
	teamId: text("team_id"),
	year: text("year"),
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	divisionId: text("division_id"),
	levelId: text("level_id"),
	splitId: text("split_id"),
	position: text("position"),
	g: text("g"),
	gs: text("gs"),
	tc: text("tc"),
	a: text("a"),
	po: text("po"),
	e: text("e"),
	dp: text("dp"),
	tp: text("tp"),
	pb: text("pb"),
	sba: text("sba"),
	rto: text("rto"),
	er: text("er"),
	ip: text("ip"),
	ipf: text("ipf"),
	pct: text("pct"),
	range: text("range"),
	rtop: text("rtop"),
	cera: text("cera"),
});

export const teamHistoryFinancials = sqliteTable("team_history_financials", {
	teamId: text("team_id"),
	year: text("year"),
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	divisionId: text("division_id"),
	gateRevenue: text("gate_revenue"),
	gateShareGained: text("gate_share_gained"),
	gateShareLost: text("gate_share_lost"),
	seasonTicketRevenue: text("season_ticket_revenue"),
	mediaRevenue: text("media_revenue"),
	merchandisingRevenue: text("merchandising_revenue"),
	revenueSharing: text("revenue_sharing"),
	luxurySharing: text("luxury_sharing"),
	playoffRevenue: text("playoff_revenue"),
	cash: text("cash"),
	cashOwner: text("cash_owner"),
	cashTrades: text("cash_trades"),
	previousBalance: text("previous_balance"),
	playerExpenses: text("player_expenses"),
	staffExpenses: text("staff_expenses"),
	stadiumExpenses: text("stadium_expenses"),
	seasonTickets: text("season_tickets"),
	attendance: text("attendance"),
	fanInterest: text("fan_interest"),
	fanLoyalty: text("fan_loyalty"),
	fanModifier: text("fan_modifier"),
	ticketPrice: text("ticket_price"),
	localMediaContract: text("local_media_contract"),
	localMediaContractExpires: text("local_media_contract_expires"),
	nationalMediaContract: text("national_media_contract"),
	nationalMediaContractExpires: text("national_media_contract_expires"),
	scoutingBudget: text("scouting_budget"),
	developmentBudget: text("development_budget"),
	draftBudget: text("draft_budget"),
	draftExpenses: text("draft_expenses"),
	intlFaBudget: text("intl_fa_budget"),
	spentInIntl: text("spent_in_intl"),
	budget: text("budget"),
	market: text("market"),
	ownerExpectation: text("owner_expectation"),
	totalRevenue: text("total_revenue"),
	totalExpenses: text("total_expenses"),
	financialBalance: text("financial_balance"),
	budgetBalance: text("budget_balance"),
});

export const teamHistoryPitchingStats = sqliteTable("team_history_pitching_stats", {
	teamId: text("team_id"),
	year: text("year"),
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	divisionId: text("division_id"),
	levelId: text("level_id"),
	splitId: text("split_id"),
	ab: text("ab"),
	ip: text("ip"),
	bf: text("bf"),
	tb: text("tb"),
	ha: text("ha"),
	k: text("k"),
	rs: text("rs"),
	bb: text("bb"),
	r: text("r"),
	er: text("er"),
	gb: text("gb"),
	fb: text("fb"),
	pi: text("pi"),
	ipf: text("ipf"),
	g: text("g"),
	gs: text("gs"),
	w: text("w"),
	l: text("l"),
	s: text("s"),
	sa: text("sa"),
	da: text("da"),
	sh: text("sh"),
	sf: text("sf"),
	ta: text("ta"),
	hra: text("hra"),
	bk: text("bk"),
	ci: text("ci"),
	iw: text("iw"),
	wp: text("wp"),
	hp: text("hp"),
	gf: text("gf"),
	dp: text("dp"),
	qs: text("qs"),
	svo: text("svo"),
	bs: text("bs"),
	ra: text("ra"),
	cg: text("cg"),
	sho: text("sho"),
	sb: text("sb"),
	cs: text("cs"),
	hld: text("hld"),
	r9: text("r9"),
	avg: text("avg"),
	obp: text("obp"),
	slg: text("slg"),
	ops: text("ops"),
	h9: text("h9"),
	k9: text("k9"),
	hr9: text("hr9"),
	bb9: text("bb9"),
	cgp: text("cgp"),
	fip: text("fip"),
	qsp: text("qsp"),
	winp: text("winp"),
	rsg: text("rsg"),
	svp: text("svp"),
	bsvp: text("bsvp"),
	gfp: text("gfp"),
	era: text("era"),
	pig: text("pig"),
	ws: text("ws"),
	whip: text("whip"),
	gbfbp: text("gbfbp"),
	kbb: text("kbb"),
	babip: text("babip"),
});

export const teamHistoryRecord = sqliteTable("team_history_record", {
	teamId: text("team_id"),
	year: text("year"),
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	divisionId: text("division_id"),
	g: text("g"),
	w: text("w"),
	l: text("l"),
	t: text("t"),
	pos: text("pos"),
	pct: text("pct"),
	gb: text("gb"),
	streak: text("streak"),
	magicNumber: text("magic_number"),
});

export const teamLastFinancials = sqliteTable("team_last_financials", {
	teamId: text("team_id"),
	gateRevenue: text("gate_revenue"),
	gateShareGained: text("gate_share_gained"),
	gateShareLost: text("gate_share_lost"),
	seasonTicketRevenue: text("season_ticket_revenue"),
	mediaRevenue: text("media_revenue"),
	merchandisingRevenue: text("merchandising_revenue"),
	revenueSharing: text("revenue_sharing"),
	luxurySharing: text("luxury_sharing"),
	playoffRevenue: text("playoff_revenue"),
	cash: text("cash"),
	cashOwner: text("cash_owner"),
	cashTrades: text("cash_trades"),
	previousBalance: text("previous_balance"),
	playerExpenses: text("player_expenses"),
	staffExpenses: text("staff_expenses"),
	stadiumExpenses: text("stadium_expenses"),
	seasonTickets: text("season_tickets"),
	attendance: text("attendance"),
	fanInterest: text("fan_interest"),
	fanLoyalty: text("fan_loyalty"),
	fanModifier: text("fan_modifier"),
	ticketPrice: text("ticket_price"),
	localMediaContract: text("local_media_contract"),
	localMediaContractExpires: text("local_media_contract_expires"),
	nationalMediaContract: text("national_media_contract"),
	nationalMediaContractExpires: text("national_media_contract_expires"),
	scoutingBudget: text("scouting_budget"),
	developmentBudget: text("development_budget"),
	draftBudget: text("draft_budget"),
	draftExpenses: text("draft_expenses"),
	intlFaBudget: text("intl_fa_budget"),
	spentInIntl: text("spent_in_intl"),
	budget: text("budget"),
	market: text("market"),
	ownerExpectation: text("owner_expectation"),
	totalRevenue: text("total_revenue"),
	totalExpenses: text("total_expenses"),
	financialBalance: text("financial_balance"),
	budgetBalance: text("budget_balance"),
});

export const teamPitchingStats = sqliteTable("team_pitching_stats", {
	teamId: text("team_id"),
	year: text("year"),
	leagueId: text("league_id"),
	levelId: text("level_id"),
	splitId: text("split_id"),
	ab: text("ab"),
	ip: text("ip"),
	bf: text("bf"),
	tb: text("tb"),
	ha: text("ha"),
	k: text("k"),
	rs: text("rs"),
	bb: text("bb"),
	r: text("r"),
	er: text("er"),
	gb: text("gb"),
	fb: text("fb"),
	pi: text("pi"),
	ipf: text("ipf"),
	g: text("g"),
	gs: text("gs"),
	w: text("w"),
	l: text("l"),
	s: text("s"),
	sa: text("sa"),
	da: text("da"),
	sh: text("sh"),
	sf: text("sf"),
	ta: text("ta"),
	hra: text("hra"),
	bk: text("bk"),
	ci: text("ci"),
	iw: text("iw"),
	wp: text("wp"),
	hp: text("hp"),
	gf: text("gf"),
	dp: text("dp"),
	qs: text("qs"),
	svo: text("svo"),
	bs: text("bs"),
	ra: text("ra"),
	cg: text("cg"),
	sho: text("sho"),
	sb: text("sb"),
	cs: text("cs"),
	hld: text("hld"),
	r9: text("r9"),
	avg: text("avg"),
	obp: text("obp"),
	slg: text("slg"),
	ops: text("ops"),
	h9: text("h9"),
	k9: text("k9"),
	hr9: text("hr9"),
	bb9: text("bb9"),
	cgp: text("cgp"),
	fip: text("fip"),
	qsp: text("qsp"),
	winp: text("winp"),
	rsg: text("rsg"),
	svp: text("svp"),
	bsvp: text("bsvp"),
	gfp: text("gfp"),
	era: text("era"),
	pig: text("pig"),
	ws: text("ws"),
	whip: text("whip"),
	gbfbp: text("gbfbp"),
	kbb: text("kbb"),
	babip: text("babip"),
});

export const teamRecord = sqliteTable("team_record", {
	teamId: text("team_id"),
	g: text("g"),
	w: text("w"),
	l: text("l"),
	t: text("t"),
	pos: text("pos"),
	pct: text("pct"),
	gb: text("gb"),
	streak: text("streak"),
	magicNumber: text("magic_number"),
});

export const teamRelations = sqliteTable("team_relations", {
	leagueId: text("league_id"),
	subLeagueId: text("sub_league_id"),
	divisionId: text("division_id"),
	teamId: text("team_id"),
});
*/
export const teamRoster = sqliteTable("team_roster", {
  team_id: integer("team_id"),
  player_id: integer("player_id"),
  list_id: integer("list_id"),
}, (table) => {
  return {
    team_roster_player_id_idx: index("team_roster_player_id_idx").on(
      table.player_id,
    ),
    team_roster_team_id_idx: index("team_roster_team_id_idx").on(table.team_id),
    team_roster_list_id_idx: index("team_roster_list_id_idx").on(table.list_id),
  };
});
/*
export const teamRosterStaff = sqliteTable("team_roster_staff", {
	teamId: text("team_id"),
	headScout: text("head_scout"),
	manager: text("manager"),
	generalManager: text("general_manager"),
	pitchingCoach: text("pitching_coach"),
	hittingCoach: text("hitting_coach"),
	benchCoach: text("bench_coach"),
	owner: text("owner"),
	doctor: text("doctor"),
	firstBaseCoach: text("first_base_coach"),
	thirdBaseCoach: text("third_base_coach"),
});

export const teamStartingPitchingStats = sqliteTable("team_starting_pitching_stats", {
	team_id: text("team_id"),
	year: text("year"),
	league_id: text("league_id"),
	level_id: text("level_id"),
	split_id: text("split_id"),
	ab: text("ab"),
	ip: text("ip"),
	bf: text("bf"),
	tb: text("tb"),
	ha: text("ha"),
	k: text("k"),
	rs: text("rs"),
	bb: text("bb"),
	r: text("r"),
	er: text("er"),
	gb: text("gb"),
	fb: text("fb"),
	pi: text("pi"),
	ipf: text("ipf"),
	g: text("g"),
	gs: text("gs"),
	w: text("w"),
	l: text("l"),
	s: text("s"),
	sa: text("sa"),
	da: text("da"),
	sh: text("sh"),
	sf: text("sf"),
	ta: text("ta"),
	hra: text("hra"),
	bk: text("bk"),
	ci: text("ci"),
	iw: text("iw"),
	wp: text("wp"),
	hp: text("hp"),
	gf: text("gf"),
	dp: text("dp"),
	qs: text("qs"),
	svo: text("svo"),
	bs: text("bs"),
	ra: text("ra"),
	cg: text("cg"),
	sho: text("sho"),
	sb: text("sb"),
	cs: text("cs"),
	hld: text("hld"),
	r9: text("r9"),
	avg: text("avg"),
	obp: text("obp"),
	slg: text("slg"),
	ops: text("ops"),
	h9: text("h9"),
	k9: text("k9"),
	hr9: text("hr9"),
	bb9: text("bb9"),
	cgp: text("cgp"),
	fip: text("fip"),
	qsp: text("qsp"),
	winp: text("winp"),
	rsg: text("rsg"),
	svp: text("svp"),
	bsvp: text("bsvp"),
	gfp: text("gfp"),
	era: text("era"),
	pig: text("pig"),
	ws: text("ws"),
	whip: text("whip"),
	gbfbp: text("gbfbp"),
	kbb: text("kbb"),
	babip: text("babip"),
});
*/
export const teams = sqliteTable("teams", {
  team_id: integer("team_id"),
  name: text("name"),
  abbr: text("abbr"),
  nickname: text("nickname"),
  logo_file_name: text("logo_file_name"),
  city_id: integer("city_id"),
  park_id: integer("park_id"),
  league_id: integer("league_id"),
  sub_league_id: integer("sub_league_id"),
  division_id: integer("division_id"),
  nation_id: integer("nation_id"),
  parent_team_id: integer("parent_team_id"),
  level: integer("level"),
  prevent_any_moves: integer("prevent_any_moves"),
  human_team: integer("human_team"),
  human_id: integer("human_id"),
  gender: integer("gender"),
  background_color_id: text("background_color_id"),
  text_color_id: text("text_color_id"),
  ballcaps_main_color_id: text("ballcaps_main_color_id"),
  ballcaps_visor_color_id: text("ballcaps_visor_color_id"),
  jersey_main_color_id: text("jersey_main_color_id"),
  jersey_away_color_id: text("jersey_away_color_id"),
  jersey_secondary_color_id: text("jersey_secondary_color_id"),
  jersey_pin_stripes_color_id: text("jersey_pin_stripes_color_id"),
  allstar_team: integer("allstar_team"),
  historical_id: text("historical_id"),
}, (table) => {
  return {
    teamIdIdx: uniqueIndex("team_id_idx").on(table.team_id),
  };
});
/*
export const tradeHistory = sqliteTable("trade_history", {
	date: text("date"),
	summary: text("summary"),
	messageId: text("message_id"),
	teamId0: text("team_id_0"),
	playerId00: text("player_id_0_0"),
	playerId01: text("player_id_0_1"),
	playerId02: text("player_id_0_2"),
	playerId03: text("player_id_0_3"),
	playerId04: text("player_id_0_4"),
	playerId05: text("player_id_0_5"),
	playerId06: text("player_id_0_6"),
	playerId07: text("player_id_0_7"),
	playerId08: text("player_id_0_8"),
	playerId09: text("player_id_0_9"),
	draftRound00: text("draft_round_0_0"),
	draftTeam00: text("draft_team_0_0"),
	draftRound01: text("draft_round_0_1"),
	draftTeam01: text("draft_team_0_1"),
	draftRound02: text("draft_round_0_2"),
	draftTeam02: text("draft_team_0_2"),
	draftRound03: text("draft_round_0_3"),
	draftTeam03: text("draft_team_0_3"),
	draftRound04: text("draft_round_0_4"),
	draftTeam04: text("draft_team_0_4"),
	cash0: text("cash_0"),
	iafaCap0: text("iafa_cap_0"),
	teamId1: text("team_id_1"),
	playerId10: text("player_id_1_0"),
	playerId11: text("player_id_1_1"),
	playerId12: text("player_id_1_2"),
	playerId13: text("player_id_1_3"),
	playerId14: text("player_id_1_4"),
	playerId15: text("player_id_1_5"),
	playerId16: text("player_id_1_6"),
	playerId17: text("player_id_1_7"),
	playerId18: text("player_id_1_8"),
	playerId19: text("player_id_1_9"),
	draftRound10: text("draft_round_1_0"),
	draftTeam10: text("draft_team_1_0"),
	draftRound11: text("draft_round_1_1"),
	draftTeam11: text("draft_team_1_1"),
	draftRound12: text("draft_round_1_2"),
	draftTeam12: text("draft_team_1_2"),
	draftRound13: text("draft_round_1_3"),
	draftTeam13: text("draft_team_1_3"),
	draftRound14: text("draft_round_1_4"),
	draftTeam14: text("draft_team_1_4"),
	cash1: text("cash_1"),
	iafaCap1: text("iafa_cap_1"),
});
*/
