import { index, numeric, sqliteTable, text } from 'drizzle-orm/sqlite-core'

export const PlayersTable = sqliteTable('players', {
  player_id: numeric('player_id'),
  team_id: numeric('team_id'),
  first_name: text('first_name'),
  last_name: text('last_name'),
  position: numeric('position'),
  age: numeric('age'),
  role: numeric('role'),
  bats: numeric('bats'),
  roster: text('roster'),

  batting_ratings_overall_contact: numeric('batting_ratings_overall_contact'),
  batting_ratings_overall_gap: numeric('batting_ratings_overall_gap'),
  batting_ratings_overall_eye: numeric('batting_ratings_overall_eye'),
  batting_ratings_overall_strikeouts: numeric('batting_ratings_overall_strikeouts'),
  batting_ratings_overall_hp: numeric('batting_ratings_overall_hp'),
  batting_ratings_overall_power: numeric('batting_ratings_overall_power'),
  batting_ratings_overall_babip: numeric('batting_ratings_overall_babip'),
  batting_ratings_vsr_contact: numeric('batting_ratings_vsr_contact'),
  batting_ratings_vsr_gap: numeric('batting_ratings_vsr_gap'),
  batting_ratings_vsr_eye: numeric('batting_ratings_vsr_eye'),
  batting_ratings_vsr_strikeouts: numeric('batting_ratings_vsr_strikeouts'),
  batting_ratings_vsr_hp: numeric('batting_ratings_vsr_hp'),
  batting_ratings_vsr_power: numeric('batting_ratings_vsr_power'),
  batting_ratings_vsr_babip: numeric('batting_ratings_vsr_babip'),
  batting_ratings_vsl_contact: numeric('batting_ratings_vsl_contact'),
  batting_ratings_vsl_gap: numeric('batting_ratings_vsl_gap'),
  batting_ratings_vsl_eye: numeric('batting_ratings_vsl_eye'),
  batting_ratings_vsl_strikeouts: numeric('batting_ratings_vsl_strikeouts'),
  batting_ratings_vsl_hp: numeric('batting_ratings_vsl_hp'),
  batting_ratings_vsl_power: numeric('batting_ratings_vsl_power'),
  batting_ratings_vsl_babip: numeric('batting_ratings_vsl_babip'),
  batting_ratings_talent_contact: numeric('batting_ratings_talent_contact'),
  batting_ratings_talent_gap: numeric('batting_ratings_talent_gap'),
  batting_ratings_talent_eye: numeric('batting_ratings_talent_eye'),
  batting_ratings_talent_strikeouts: numeric('batting_ratings_talent_strikeouts'),
  batting_ratings_talent_hp: numeric('batting_ratings_talent_hp'),
  batting_ratings_talent_power: numeric('batting_ratings_talent_power'),
  batting_ratings_talent_babip: numeric('batting_ratings_talent_babip'),
  batting_ratings_misc_bunt: numeric('batting_ratings_misc_bunt'),
  batting_ratings_misc_bunt_for_hit: numeric('batting_ratings_misc_bunt_for_hit'),
  batting_ratings_misc_gb_hitter_type: numeric('batting_ratings_misc_gb_hitter_type'),
  batting_ratings_misc_fb_hitter_type: numeric('batting_ratings_misc_fb_hitter_type'),

  pitching_ratings_overall_stuff: numeric('pitching_ratings_overall_stuff'),
  pitching_ratings_overall_control: numeric('pitching_ratings_overall_control'),
  pitching_ratings_overall_movement: numeric('pitching_ratings_overall_movement'),
  pitching_ratings_overall_balk: numeric('pitching_ratings_overall_balk'),
  pitching_ratings_overall_hp: numeric('pitching_ratings_overall_hp'),
  pitching_ratings_overall_wild_pitch: numeric('pitching_ratings_overall_wild_pitch'),
  pitching_ratings_vsr_stuff: numeric('pitching_ratings_vsr_stuff'),
  pitching_ratings_vsr_control: numeric('pitching_ratings_vsr_control'),
  pitching_ratings_vsr_movement: numeric('pitching_ratings_vsr_movement'),
  pitching_ratings_vsr_balk: numeric('pitching_ratings_vsr_balk'),
  pitching_ratings_vsr_hp: numeric('pitching_ratings_vsr_hp'),
  pitching_ratings_vsr_wild_pitch: numeric('pitching_ratings_vsr_wild_pitch'),
  pitching_ratings_vsl_stuff: numeric('pitching_ratings_vsl_stuff'),
  pitching_ratings_vsl_control: numeric('pitching_ratings_vsl_control'),
  pitching_ratings_vsl_movement: numeric('pitching_ratings_vsl_movement'),
  pitching_ratings_vsl_balk: numeric('pitching_ratings_vsl_balk'),
  pitching_ratings_vsl_hp: numeric('pitching_ratings_vsl_hp'),
  pitching_ratings_vsl_wild_pitch: numeric('pitching_ratings_vsl_wild_pitch'),
  pitching_ratings_talent_stuff: numeric('pitching_ratings_talent_stuff'),
  pitching_ratings_talent_control: numeric('pitching_ratings_talent_control'),
  pitching_ratings_talent_movement: numeric('pitching_ratings_talent_movement'),
  pitching_ratings_talent_balk: numeric('pitching_ratings_talent_balk'),
  pitching_ratings_talent_hp: numeric('pitching_ratings_talent_hp'),
  pitching_ratings_talent_wild_pitch: numeric('pitching_ratings_talent_wild_pitch'),
  pitching_ratings_pitches_fastball: numeric('pitching_ratings_pitches_fastball'),
  pitching_ratings_pitches_slider: numeric('pitching_ratings_pitches_slider'),
  pitching_ratings_pitches_curveball: numeric('pitching_ratings_pitches_curveball'),
  pitching_ratings_pitches_screwball: numeric('pitching_ratings_pitches_screwball'),
  pitching_ratings_pitches_forkball: numeric('pitching_ratings_pitches_forkball'),
  pitching_ratings_pitches_changeup: numeric('pitching_ratings_pitches_changeup'),
  pitching_ratings_pitches_sinker: numeric('pitching_ratings_pitches_sinker'),
  pitching_ratings_pitches_splitter: numeric('pitching_ratings_pitches_splitter'),
  pitching_ratings_pitches_knuckleball: numeric('pitching_ratings_pitches_knuckleball'),
  pitching_ratings_pitches_cutter: numeric('pitching_ratings_pitches_cutter'),
  pitching_ratings_pitches_circlechange: numeric('pitching_ratings_pitches_circlechange'),
  pitching_ratings_pitches_knucklecurve: numeric('pitching_ratings_pitches_knucklecurve'),
  pitching_ratings_pitches_talent_fastball: numeric('pitching_ratings_pitches_talent_fastball'),
  pitching_ratings_pitches_talent_slider: numeric('pitching_ratings_pitches_talent_slider'),
  pitching_ratings_pitches_talent_curveball: numeric('pitching_ratings_pitches_talent_curveball'),
  pitching_ratings_pitches_talent_screwball: numeric('pitching_ratings_pitches_talent_screwball'),
  pitching_ratings_pitches_talent_forkball: numeric('pitching_ratings_pitches_talent_forkball'),
  pitching_ratings_pitches_talent_changeup: numeric('pitching_ratings_pitches_talent_changeup'),
  pitching_ratings_pitches_talent_sinker: numeric('pitching_ratings_pitches_talent_sinker'),
  pitching_ratings_pitches_talent_splitter: numeric('pitching_ratings_pitches_talent_splitter'),
  pitching_ratings_pitches_talent_knuckleball: numeric('pitching_ratings_pitches_talent_knuckleball'),
  pitching_ratings_pitches_talent_cutter: numeric('pitching_ratings_pitches_talent_cutter'),
  pitching_ratings_pitches_talent_circlechange: numeric('pitching_ratings_pitches_talent_circlechange'),
  pitching_ratings_pitches_talent_knucklecurve: numeric('pitching_ratings_pitches_talent_knucklecurve'),
  pitching_ratings_misc_velocity: numeric('pitching_ratings_misc_velocity'),
  pitching_ratings_misc_arm_slot: numeric('pitching_ratings_misc_arm_slot'),
  pitching_ratings_misc_stamina: numeric('pitching_ratings_misc_stamina'),
  pitching_ratings_misc_ground_fly: numeric('pitching_ratings_misc_ground_fly'),
  pitching_ratings_misc_hold: numeric('pitching_ratings_misc_hold'),
  pitching_ratings_babip: numeric('pitching_ratings_babip'),
}, (table) => {
  return {
    player_id_idx: index('player_id_idx').on(table.player_id),
    team_id_idx: index('team_id_idx').on(table.team_id),
  }
})

export type Player = typeof PlayersTable.$inferSelect

export const TeamsTable = sqliteTable('teams', {
  team_id: numeric('team_id'),
  name: text('name'),
  abbr: text('abbr'),
  nickname: text('nickname'),
  logo_file_name: text('logo_file_name'),
}, (table) => {
  return {
    team_id_idx: index('team_id_idx').on(table.team_id),
  }
})
export type Team = typeof TeamsTable.$inferSelect
